/**
 * Berufsbezeichnungen als Vorschlagsliste für die Zusatzqualifikationen einer
 * Person (Ebene der Berufsuntergruppen der KldB 2010, 700 Einträge).
 *
 * GENERIERT — nicht von Hand bearbeiten.
 * Quelle: Klassifikation der Berufe 2010 der Bundesagentur für Arbeit,
 * scripts/quellen/kldb-2010-berufe.csv.
 * Neu erzeugen mit:  npx tsx scripts/berufe-vokabular.mts
 *
 * Bewusst nur Strings, keine Codes: ein Beruf wandert als Freitext in den Bogen.
 * Die Liste ist reine Tipphilfe — eigene Eingaben bleiben immer möglich —, und
 * so bleibt das QR-Format unberührt (kein Schema-Sprung, alte Bögen lesbar).
 */

export const BERUFE: readonly string[] = [
  "(Fremd-)Sprachenlehrer/innen",
  "Abfallwirtschaft",
  "Altenpflege",
  "Altenpflege (sonstige Spezialtätigkeit)",
  "Altphilologie",
  "Angehörige der regulären Streitkräfte in sonstigen Rängen",
  "Angehörige geistlicher Orden und Mutterhäuser",
  "Angehörige gesetzgebender Körperschaften",
  "Anglistik und Amerikanistik",
  "Animateure/-innen und Gästebetreuer/innen",
  "Anlageberater/innen und sonstige Finanzdienstleistungen",
  "Anlagen-, Behälter- und Apparatebau",
  "Anthropologie und Ethnologie",
  "Apotheker/innen, Pharmazeuten/Pharmazeutinnen",
  "Arabistik und Orientalistik",
  "Arbeitssicherheit und Sicherheitstechnik",
  "Archäologie",
  "Architektur",
  "Archivwesen",
  "Ärzte/Ärztinnen",
  "Ärzte/Ärztinnen (sonstige Spezialtätigkeit)",
  "Assistenzkräfte Rechtsanwaltskanzlei und Notariat",
  "Athleten/Athletinnen und Berufssportler/innen",
  "Aufsichts- und Führungskräfte Bauplanung und -überwachung, Architektur",
  "Aufsichts- und Führungskräfte Berg- und Tagebau und Sprengtechnik",
  "Aufsichts- und Führungskräfte Bestattungswesen",
  "Aufsichts- und Führungskräfte Biologie",
  "Aufsichts- und Führungskräfte Chemie",
  "Aufsichts- und Führungskräfte Erziehung, Sozialarbeit, Heilerziehungspflege",
  "Aufsichts- und Führungskräfte Fahrzeug, Luft-, Raumfahrt- und Schiffbautechnik",
  "Aufsichts- und Führungskräfte Fischwirtschaft",
  "Aufsichts- und Führungskräfte Floristik",
  "Aufsichts- und Führungskräfte Forst- und Jagdwirtschaft, Landschaftspflege",
  "Aufsichts- und Führungskräfte Gartenbau",
  "Aufsichts- und Führungskräfte Gastronomie und Systemgastronomie",
  "Aufsichts- und Führungskräfte Gesundheits- und Krankenpflege, Rettungsdienst und Geburtshilfe",
  "Aufsichts- und Führungskräfte Getränkeherstellung",
  "Aufsichts- und Führungskräfte Gewerbe- und Gesundheitsaufsicht, Desinfektion",
  "Aufsichts- und Führungskräfte Holzbe- und -verarbeitung",
  "Aufsichts- und Führungskräfte Hotellerie",
  "Aufsichts- und Führungskräfte Lagerwirtschaft, Post und Zustellung, Güterumschlag",
  "Aufsichts- und Führungskräfte Landwirtschaft",
  "Aufsichts- und Führungskräfte Lebensmittel- und Genussmittelherstellung",
  "Aufsichts- und Führungskräfte Leder-, Pelzherstellung und -verarbeitung",
  "Aufsichts- und Führungskräfte Maschinenbau- und Betriebstechnik",
  "Aufsichts- und Führungskräfte Medizin-, Orthopädie- und Rehatechnik",
  "Aufsichts- und Führungskräfte Objektschutz, Personen-, Brandschutz, Arbeitssicherheit",
  "Aufsichts- und Führungskräfte Pferdewirtschaft",
  "Aufsichts- und Führungskräfte Physik",
  "Aufsichts- und Führungskräfte Speisenzubereitung",
  "Aufsichts- und Führungskräfte Technische Mediengestaltung",
  "Aufsichts- und Führungskräfte Technische Produktionsplanung und -steuerung",
  "Aufsichts- und Führungskräfte Technisches Zeichnen, Konstruktion und Modellbau",
  "Aufsichts- und Führungskräfte Textiltechnik und -produktion",
  "Aufsichts- und Führungskräfte Textilverarbeitung",
  "Aufsichts- und Führungskräfte Theater-, Film- und Fernsehproduktion",
  "Aufsichts- und Führungskräfte Tierpflege",
  "Aufsichts- und Führungskräfte Tierwirtschaft",
  "Aufsichts- und Führungskräfte Überwachung und Steuerung Verkehrsbetrieb",
  "Aufsichts- und Führungskräfte Unternehmensorganisation und -strategie",
  "Aufsichts- und Führungskräfte Verkauf",
  "Aufsichts- und Führungskräfte Verwaltung",
  "Aufsichts- und Führungskräfte Weinbau",
  "Aufsichtskräfte Bau- und Transportgeräteführung",
  "Aufsichtskräfte Bodenverlegung",
  "Aufsichtskräfte Bühnen- und Kostümbildnerei, Requisite",
  "Aufsichtskräfte Büro und Sekretariat",
  "Aufsichtskräfte Drucktechnik und -weiterverarbeitung, Buchbinderei",
  "Aufsichtskräfte Elektrotechnik",
  "Aufsichtskräfte Energietechnik",
  "Aufsichtskräfte Farb- und Lacktechnik",
  "Aufsichtskräfte Feinwerk- und Werkzeugtechnik",
  "Aufsichtskräfte Fototechnik und Fotografie",
  "Aufsichtskräfte Gebäudetechnik",
  "Aufsichtskräfte Hauswirtschaft und Verbraucherberatung",
  "Aufsichtskräfte Hochbau",
  "Aufsichtskräfte Industrielle Glasherstellung und -verarbeitung",
  "Aufsichtskräfte Industrielle Keramikherstellung und -verarbeitung",
  "Aufsichtskräfte Innenarchitektur, visuelles Marketing, Raumausstattung",
  "Aufsichtskräfte Klempnerei, Sanitär-, Heizungs- und Klimatechnik",
  "Aufsichtskräfte Körperpflege",
  "Aufsichtskräfte Kunsthandwerk und bildende Kunst",
  "Aufsichtskräfte Kunsthandwerkliche Keramik- und Glasgestaltung",
  "Aufsichtskräfte Kunsthandwerkliche Metallgestaltung",
  "Aufsichtskräfte Kunststoff- und Kautschukherstellung und -verarbeitung",
  "Aufsichtskräfte Maler-, Stuckateurarbeiten, Bauwerksabdichtung, Holz und Bautenschutz",
  "Aufsichtskräfte Mechatronik und Automatisierungstechnik",
  "Aufsichtskräfte Metallbau und Schweißtechnik",
  "Aufsichtskräfte Metallbearbeitung",
  "Aufsichtskräfte Metallerzeugung",
  "Aufsichtskräfte Metalloberflächenbehandlung",
  "Aufsichtskräfte Musikinstrumentenbau",
  "Aufsichtskräfte Naturstein- und Mineralaufbereitung und -verarbeitung und Baustoffherstellung",
  "Aufsichtskräfte Papier- und Verpackungstechnik",
  "Aufsichtskräfte Personenverkehr (Servicebereich)",
  "Aufsichtskräfte Reinigung",
  "Aufsichtskräfte Technischer Betrieb Eisenbahn-, Luft- und Schiffsverkehr",
  "Aufsichtskräfte Tiefbau",
  "Aufsichtskräfte Trockenbau, Isolierung, Zimmerei, Glaserei, Rollladenbau",
  "Aufsichtskräfte Überwachung und Wartung der Verkehrsinfrastruktur",
  "Aufsichtskräfte Umweltschutztechnik",
  "Aufsichtskräfte Ver- und Entsorgung",
  "Aufsichtskräfte Veranstaltungs-, Kamera- und Tontechnik",
  "Augenoptik",
  "Aus- und Trockenbau",
  "Auskunft und Kundeninformation",
  "Automatisierungstechnik",
  "Autoren/Autorinnen und Schriftsteller/innen",
  "Back- und Konditoreiwarenherstellung",
  "Badeaufsicht",
  "Bankkaufleute",
  "Barkeeper/innen",
  "Bauabrechnung und -kalkulation",
  "Bauelektrik",
  "Baumschule, Staudengärtnerei und Zierpflanzenbau",
  "Bauplanung und -überwachung",
  "Bauplanung Verkehrswege und -anlagen",
  "Bausachverständige und Baukontrolleure/-innen",
  "Baustoffherstellung",
  "Baustoffprüfung",
  "Bautischlerei",
  "Bauwerksabbruch",
  "Bauwerksabdichtung",
  "Bauwerkserhaltung und -erneuerung",
  "Bekleidungs-, Hut- und Mützenherstellung",
  "Berg- und Tagebau",
  "Berufskraftfahrer/innen (Güterverkehr/LKW)",
  "Berufskraftfahrer/innen (Personentransport/PKW)",
  "Bestattungswesen",
  "Beton- und Stahlbetonbau",
  "Betrieb Eisenb, Luft und Schiffsverkehr (sonstige Spezialtätigkeit)",
  "Betriebliche Ausbildung und Betriebspädagogik",
  "Betriebsinterne Wahlämter",
  "Bibliothekswesen",
  "Bild- und Tontechnik",
  "Bildhauerei",
  "Bio- und Medizininformatik",
  "Biologie",
  "Biologie (Botanik)",
  "Biologie (Humanbiologie)",
  "Biologie (Mikrobiologie)",
  "Biologie (Ökologie)",
  "Biologie (sonstige Spezialtätigkeit)",
  "Biologie (Zoologie)",
  "Biologisch-technisches Laboratorium",
  "Biologische Präparation",
  "Bodenverlegung",
  "Brandschutz",
  "Brauer/innen und Mälzer/innen",
  "Brenner/innen und Destillateure/-innen",
  "Brunnenbau",
  "Buchbinderei und Druckweiterverarbeitung",
  "Buchhaltung",
  "Buchhandel",
  "Bühnen- und Kostümbildnerei",
  "Büro- und Sekretariatskräfte",
  "Bus- und Straßenbahnfahrer/innen",
  "Chemie",
  "Chemie (sonstige Spezialtätigkeit)",
  "Chemie- und Pharmatechnik",
  "Chemisch-technisches Laboratorium",
  "Controlling",
  "Dachdeckerei",
  "Datenbankentwicklung und -administration",
  "Demografie",
  "Desinfektion und Schädlingsbekämpfung",
  "Detektive/Detektivinnen",
  "Dialogmarketing",
  "Diät- und Ernährungstherapie",
  "Digital- und Printmediengestaltung",
  "Dirigenten/Dirigentinnen",
  "Dokumentations- und Informationsdienst",
  "Dolmetscher/innen und Übersetzer/innen",
  "Drechslerei und Spielzeugherstellung",
  "Drucktechnik",
  "Einkauf",
  "Elektrische Betriebstechnik",
  "Elektromaschinentechnik",
  "Elektrotechnik",
  "Elektrotechnik (sonstige Spezialtätigkeit)",
  "Energie- und Kraftwerkstechnik",
  "Ergotherapie",
  "Ernährung und Gesundheitsberatung, Wellness (sonstige Spezialtätigkeit)",
  "Ernährungsberatung",
  "Erwachsenenbildung",
  "Erziehungswissenschaft",
  "Estrich- und Terrazzoverlegung",
  "Fachärzte Hautkrankheiten, Sinnes und Geschlechtsorgane",
  "Fachärzte Neurologie, Psychiatrie, Psychotherapie und psychosomatische Medizin",
  "Fachärzte/-ärztinnen Anästhesiologie",
  "Fachärzte/-ärztinnen Chirurgie",
  "Fachärzte/-ärztinnen Innere Medizin",
  "Fachärzte/-ärztinnen Kinder- und Jugendmedizin",
  "Fachärzte/-ärztinnen Pharmakologie",
  "Fachkinderkrankenpflege",
  "Fachkrankenpflege",
  "Facility-Management",
  "Fahrlehrer/innen",
  "Fahrzeugführung Flugverkehr (sonstige Spezialtätigkeit)",
  "Fahrzeugführung Straßenverkehr (sonstige Spezialtätigkeit)",
  "Fahrzeuglackierung",
  "Fahrzeugreinigung",
  "Fahrzeugtechnik",
  "Farb- und Lacktechnik",
  "Fassadenbau",
  "Feinoptik",
  "Feinwerktechnik",
  "Finanzanalysten/-analystinnen",
  "Fischerei",
  "Fischverarbeitung",
  "Fischwirtschaft",
  "Fischzucht",
  "Flechtwerkgestaltung, Bürsten- und Pinselmacher",
  "Fleischverarbeitung",
  "Fliesen-, Platten- und Mosaikverlegung",
  "Floristik",
  "Fluglehrer/innen",
  "Flugsicherungstechnik",
  "Forstwirtschaft",
  "Fotografie",
  "Fototechnik",
  "Fremdsprachensekretäre und -korrespondenten",
  "Friedhofsgärtnerei",
  "Friseurgewerbe",
  "Fruchtsafttechnik",
  "Führer/innen Erdbewegungs- und verwandte Maschinen",
  "Führer/innen land- und forstwirtschaftliche Maschinen",
  "Führungskräfte Allgemeinbildende Schulen",
  "Führungskräfte Altenpflege",
  "Führungskräfte Außerschulische Bildungseinrichtungen",
  "Führungskräfte Berufsschulen, betriebliche Ausbildung und Betriebspädagogik",
  "Führungskräfte Einkauf und Vertrieb",
  "Führungskräfte Handel",
  "Führungskräfte Hochschullehre und -forschung",
  "Führungskräfte Human- und Zahnmedizin",
  "Führungskräfte Immobilienwirtschaft und Facility-Management",
  "Führungskräfte Informatik",
  "Führungskräfte IT-Netzwerktechnik, IT-Koordination, IT-Administration und IT-Organisation",
  "Führungskräfte IT-Systemanalyse, IT-Anwendungsberatung und IT-Vertrieb",
  "Führungskräfte Mathematik und Statistik",
  "Führungskräfte Medien-, Dokumentations- und Informationsdienste",
  "Führungskräfte Medizinisches Laboratorium",
  "Führungskräfte Museum",
  "Führungskräfte Nicht ärztliche Therapie und Heilkunde",
  "Führungskräfte Öffentlichkeitsarbeit",
  "Führungskräfte Personalwesen und -dienstleistung",
  "Führungskräfte Pharmazie",
  "Führungskräfte Rechnungswesen, Controlling und Revision",
  "Führungskräfte Rechtsberatung, -sprechung und -ordnung",
  "Führungskräfte Redaktion und Journalismus",
  "Führungskräfte Softwareentwicklung und Programmierung",
  "Führungskräfte Technische Forschung und Entwicklung",
  "Führungskräfte Theologie und Gemeindearbeit",
  "Führungskräfte Tiermedizin und Tierheilkunde",
  "Führungskräfte Tourismus und Sport",
  "Führungskräfte Umweltmanagement und -beratung",
  "Führungskräfte Verkehr und Logistik (kaufmännischer Bereich)",
  "Führungskräfte Verlags- und Medienwirtschaft",
  "Führungskräfte Versicherungs- und Finanzdienstleistungen",
  "Führungskräfte Werbung und Marketing",
  "Garn- und Seilherstellung",
  "Garten-, Landschafts- und Sportplatzbau",
  "Gartenbau",
  "Gastronomie (sonstige Spezialtätigkeit)",
  "Gastronomieservice",
  "Gebäudereinigung",
  "Gebäudetechnik",
  "Geburtshilfe und Entbindungspflege",
  "Geflügelhaltung",
  "Geld- und Pfandverleih",
  "Gemeindearbeit",
  "Geografie",
  "Geoinformatik",
  "Geologie",
  "Geotechnik",
  "Gerichtsvollzug",
  "Germanistik",
  "Gerüstbau",
  "Geschäftsführer/innen und Vorstände",
  "Geschichtswissenschaften",
  "Gesellschaftswissenschaften (sonstige Spezialtätigkeit)",
  "Gesundheits- und Krankenpflege",
  "Gesundheits- und Krankenpflege (sonstige Spezialtätigkeit)",
  "Gesundheitsaufsicht und Hygieneüberwachung",
  "Gesundheitsberatung",
  "Getränkeherstellung",
  "Gewässer-, Immissionsschutz- und Abfallbeauftragte",
  "Gewerbeaufsicht",
  "Glas- und Fensterreinigung",
  "Glasapparatebau",
  "Glasapparatejustierung",
  "Glaserei",
  "Glasherstellung",
  "Glasveredelung",
  "Gleisbau",
  "Glücks- und Wettspiel",
  "Grafik-, Kommunikations- und Fotodesign",
  "Gravur",
  "Grill-, Braten- und Fischköche/-köchinnen",
  "Güter- und Warenumschlag",
  "Handelsmakler/innen und Auktionatoren/-innen",
  "Handwerkliche Metall- und Glockengießerei",
  "Haus- und Familienpflege",
  "Haus- und Zootierpflege",
  "Hauswirtschaft",
  "Heilerziehungspflege und Sonderpädagogik",
  "Heilkunde und Homöopathie",
  "Hochbau",
  "Hochschullehre und -forschung",
  "Holz- und Bautenschutz",
  "Holz-, Möbel- und Innenausbau",
  "Holzbe- und -verarbeitung",
  "Holzbe- und verarbeitung (sonstige Spezialtätigkeit)",
  "Holzblasinstrumentenbau",
  "Holztrocknung und -konservierung",
  "Hörfunk- und Fernsehmoderatoren/-moderatorinnen",
  "Hörgeräteakustik",
  "Hotelkaufleute",
  "Hotelservice",
  "Hufbeschlagschmiede/-schmiedinnen",
  "Hüttentechnik",
  "Imkerei",
  "Immobilienvermarktung und -verwaltung",
  "Industriekeramik (Modelltechnik)",
  "Industriekeramik (Verfahrens- und Anlagentechnik)",
  "Industrielle Gießerei",
  "Industrielle Glasbläserei",
  "Industrietaucher/innen und andere Taucherberufe",
  "Informatik",
  "Informations- und Telekommunikationstechnik",
  "Inkassobeauftragte",
  "Innenarchitektur",
  "Isolierung",
  "IT-Anwendungsberatung",
  "IT-Anwendungstraining",
  "IT-Koordination",
  "IT-Netzwerkadministration und -organisation (sonstige Spezialtätigkeit)",
  "IT-Netzwerktechnik",
  "IT-Organisation",
  "IT-Systemadministation",
  "IT-Systemanalyse",
  "IT-Vertrieb",
  "Jagdwirtschaft und Wildhege",
  "Justizverwaltung",
  "Justizvollzugsdienst",
  "Kältetechnik",
  "Kameratechnik",
  "Kanal- und Tunnelbau",
  "Kartografie",
  "Kassierer/innen und Kartenverkäufer/innen",
  "Kaufleute Automatenservice",
  "Kaufleute Groß- und Außenhandel",
  "Kaufleute Handel",
  "Kaufleute Handel (sonstige Spezialtätigkeit)",
  "Kaufmännische und technische Betriebswirtschaft",
  "Kinderbetreuung und -erziehung",
  "Klavier- und Cembalobau",
  "Klempnerei",
  "Klinische Psychologie",
  "Köche/Köchinnen",
  "Köche/Köchinnen (sonstige Spezialtätigkeit)",
  "Kodierer/innen, Korrekturleser/innen und verwandte Bürokräfte",
  "Komiker/innen und Kabarettisten/-innen",
  "Komponisten/Komponistinnen",
  "Konstruktion und Gerätebau",
  "Kosmetik",
  "Kostenrechnung und Kalkulation",
  "Kraftfahrzeugtechnik",
  "Kranführer/innen, Aufzugsmaschinisten und Bedienung verwandter Hebeeinrichtungen",
  "Kriminaldienst",
  "Kultur- und Wasserbau",
  "Kundenmanagement",
  "Kunst- und Antiquitätenhandel",
  "Kunst- und Theaterpädagogik",
  "Kunsthandwerk Schmuckwarenh, Edelsteine und Edelmetallbearbeitung",
  "Kunsthandwerk und bildende Kunst",
  "Kunsthandwerk und bildende Kunst (sonstige Spezialtätigkeit)",
  "Kunsthandwerkliche Glas-, Keram- und Porzellanmalerei",
  "Kunsthandwerkliche Glasbläserei",
  "Kunsthandwerkliche Keramikgestaltung",
  "Kunsthandwerkliche Metallgestaltung",
  "Kunstmaler/innen und Zeichner/innen",
  "Kunstsachverständige",
  "Kunststoff- und Kautschukherstellung",
  "Kunststoff- und Kautschukherstellung und -verarbeitung (sonstige Spezialtätigkeit)",
  "Kurier-, Express- und Postdienstleistungskaufleute",
  "Kutscher/innen",
  "Lacklaboratorium",
  "Lagerwirtschaft",
  "Land- und Baumaschinentechnik",
  "Landtechnik",
  "Landwirtschaft",
  "Landwirtschaft (sonstige Spezialtätigkeit)",
  "Landwirtschaftlich-technisches Labor",
  "Landwirtschaftliche Sachverständige",
  "Lebensmittelherstellung",
  "Lebensmittelherstellung (sonstige Spezialtätigkeit)",
  "Lebensmittelkontrolle",
  "Leder-, Pelzherstellung und -verarbeitung",
  "Lederherstellung",
  "Lehrerausbildung",
  "Lehrkräfte allgemeinbildende Schulen (sonstige Spezialtätigkeit)",
  "Lehrkräfte außerschulischer Bildungseinrichtungen (sonstige Spezialtätigkeit)",
  "Lehrkräfte berufsbildende Fächer",
  "Lehrkräfte Primarstufe",
  "Lehrkräfte Sekundarstufe",
  "Lehrkräfte Sonderschulen",
  "Leitende Bedienstete von Interessenorganisationen",
  "Leitungsinstallation und -wartung",
  "Lektoren/Lektorinnen",
  "Luft- und Raumfahrttechnik",
  "Luftverkehr, Schiffs- und Fahrzeugelektronik",
  "Luftverkehrskaufleute",
  "Maler- und Lackiererarbeiten",
  "Mannequins, Dressmen und sonstige Models",
  "Markt- und Meinungsforschung",
  "Maschinen- und Anlagenführer/innen",
  "Maschinen- und Anlagenreinigung",
  "Maschinen- und Gerätezusammensetzer/innen",
  "Maschinenbau und Betriebstechnik (sonstige Spezialtätigkeit)",
  "Maschinenbau- und Betriebstechnik",
  "Maskenbildnerei",
  "Mathematik",
  "Mathematik (sonstige Spezialtätigkeit)",
  "Maurerhandwerk",
  "Mechatronik",
  "Medien- und Theaterwissenschaft",
  "Medieninformatik",
  "Medizinisch-technische Berufe Funktionsdiagnostik",
  "Medizinisch-technische Berufe Laboratorium",
  "Medizinisch-technische Berufe Radiologie",
  "Medizinisch-technische Berufe Veterinärmedizin",
  "Medizinische Dokumentation",
  "Medizinische Fachangestellte",
  "Medizinische Fachangestellte (sonstige Spezialtätigkeit)",
  "Medizintechnik",
  "Metallbau",
  "Metallbearbeitung",
  "Metallbearbeitung durch Laserstrahl",
  "Metallblasinstrumentenbau",
  "Metallerzeugung",
  "Metalloberflächenbehandlung",
  "Metalloberflächenbehandlung (sonstige Spezialtätigkeit)",
  "Metallumformung",
  "Meteorologie",
  "Mikrosystemtechnik",
  "Milchproduktherstellung",
  "Mineralaufbereitung und -verarbeitung und Baustoffherstellung",
  "Modedesign",
  "Modellbau",
  "Moderation und Unterhaltung",
  "Moderation und Unterhaltung (sonstige Spezialtätigkeit)",
  "Mühlenprodukt- und Futtermittelherstellung",
  "Museums- und Ausstellungstechnik",
  "Museumsberufe",
  "Musik- und Kunsttherapie",
  "Musik-, Gesang- und Dirigententätigkeiten (sonstige Spezialtätigkeit)",
  "Musiker/innen",
  "Musikfachhandel",
  "Musikinstrumentenbau",
  "Musikinstrumentenbau (sonstige Spezialtätigkeit)",
  "Musikpädagogik",
  "Nahrungsmittel- und Getränkekoster/innen",
  "Natur- und Landschaftspflege",
  "Naturstein- und Mineralaufbereitung",
  "Nautische Schiffsoffiziere und Kapitäne/-innen",
  "Nicht ärztliche Psychotherapie",
  "Nicht klinische Psychologie",
  "Nichtärztliche Therapie und Heilkunde (sonstige Spezialtätigkeit)",
  "Notare/Notarinnen",
  "Nutztierhaltung (außer Geflügelhaltung)",
  "Nutztierpflege",
  "Obj, Pers, Brandsch, Arbeitssich (sonstige Spezialtätigkeit)",
  "Objekt-, Werte- und Personenschutz",
  "Obst- und Gemüsebau",
  "Ofen- und Luftheizungsbau",
  "Öffentliche Verwaltung",
  "Öffentliche Verwaltung (sonstige Spezialtätigkeit)",
  "Öffentlichkeitsarbeit",
  "Offiziere",
  "Operations-/medizintechnische Assistenz",
  "Orgel- und Harmoniumbau",
  "Orthopädie- und Rehatechnik",
  "Orthoptisten/Orthoptistinnen",
  "Papier- und Verpackungstechnik",
  "Papierherstellung",
  "Papierverarbeitung und Verpackungstechnik",
  "Parkettverlegung",
  "Pelzbe- und -verarbeitung",
  "Personaldienstleistung",
  "Personalentwicklung und -sachbearbeitung",
  "Personenbezogene Dienstleistungen",
  "Pferdewirtschaft",
  "Pferdewirtschaft-Pferdezucht",
  "Pferdewirtschaft-Reiten",
  "Pflasterer/Pflasterinnen und Steinsetzer/innen",
  "Pharmazeutisch-technische Assistenz",
  "Pharmazie (sonstige Spezialtätigkeit)",
  "Philosophie, Religion und Ethik",
  "Physik",
  "Physik (sonstige Spezialtätigkeit)",
  "Physikalisch-technisches Laboratorium",
  "Physiotherapie",
  "Piloten/Pilotinnen und Verkehrsflugzeugführer/innen",
  "Platz- und Gerätewarte/-wartinnen",
  "Podologen/Podologinnen",
  "Politologie",
  "Polizeivollzugsdienst",
  "Polsterei und Fahrzeuginnenausstattung",
  "Post- und Zustelldienste",
  "Produkt- und Industriedesign",
  "Produktion von Fertigprodukten aus Holz und Holzwerkstoffen",
  "Produktion von Holzwerkstoffen und -bauteilen",
  "Programmierung",
  "Qualitätsbeauftragte im Gesundheitswesen",
  "Raumausstattung",
  "Rechtsanwälte/-anwältinnen",
  "Rechtsberatung, -sprechung und -ordnung",
  "Rechtsberatung, -sprechung und -ordnung (sonstige Spezialtätigkeit)",
  "Redakteure/-innen und Journalisten/-innen",
  "Regenerative Energietechnik",
  "Regie",
  "Regionalwissenschaft",
  "Reifen- und Vulkanisationstechnik",
  "Reinigung",
  "Reinigung (sonstige Spezialtätigkeit)",
  "Reiseleiter/innen und Fremdenführer/innen",
  "Religionspädagogik",
  "Requisite",
  "Rettungsdienst",
  "Richter/innen",
  "Rohrleitungsbau",
  "Rollladen- und Jalousiebau",
  "Romanistik",
  "Sammeln und Gewinnen von Pflanzen und anderen Naturprodukten",
  "Sänger/innen",
  "Sanitär-, Heizungs- und Klimatechnik",
  "Sattlerei und Herstellung Lederutensilien",
  "Schauspiel, Tanz und Bewegungskunst (sonstige Spezialtätigkeit)",
  "Schauspieler/innen",
  "Schiffbautechnik",
  "Schifffahrtskaufleute",
  "Schiffsführer/innen Binnenschifffahrt und Hafenverkehr",
  "Schilder- und Lichtreklameherstellung",
  "Schleifende Metallbearbeitung",
  "Schornsteinbau",
  "Schornsteinfeger/innen",
  "Schuhherstellung",
  "Schweiß- und Verbindungstechnik",
  "Servicefachkräfte Luftverkehr",
  "Servicefachkräfte Schiffsverkehr",
  "Servicefachkräfte Straßen- und Schienenverkehr",
  "Slawistik und verwandten Bereichen",
  "Softwareentwicklung",
  "Sozial-, Erziehungs- und Suchtberatung",
  "Sozialarbeit und Sozialpädagogik",
  "Sozialverwaltung und -versicherung",
  "Soziologie",
  "Spanende Metallbearbeitung",
  "Spanlose Metallbearbeitung",
  "Speditions- und Logistikkaufleute",
  "Sport- und Fitnesskaufleute, Sportmanager/innen",
  "Sportlehrer/innen",
  "Sportlehrer/innen (sonstige Spezialtätigkeit)",
  "Sprach- und Literaturwissenschaften",
  "Sprach- und Literaturwissenschaften (sonstige Spezialtätigkeit)",
  "Sprach- und Literaturwissenschaften asiatischer Raum",
  "Sprachtherapie",
  "Sprengtechnik",
  "Staatsanwälte/-anwältinnen",
  "Stadt- und Raumplanung",
  "Statistik",
  "Steinmetztechnik",
  "Steno- und Phonotypisten/-typistinnen",
  "Steuerberatung",
  "Steuerer/-innen chemische Verfahrensanlagen",
  "Steuerer/innen Erdöl- und Erdgasraffinationsanlagen",
  "Steuerverwaltung",
  "Strahlenschutzbeauftragte",
  "Straßen- und Asphaltbau",
  "Straßen- und Schienenverkehrskaufleute",
  "Straßen- und Tunnelwärter/innen",
  "Streich- und Zupfinstrumentenbau",
  "Stuckateurarbeiten",
  "Süßwarenherstellung",
  "Systemgastronomie",
  "Tabakwarenherstellung",
  "Tänzer/innen und Choreografen/Choreografinnen",
  "Tanzlehrer/innen",
  "Tätowierer/innen und Piercer/innen",
  "Technische Forschung und Entwicklung",
  "Technische Forschung und Entwicklung (sonstige Spezialtätigkeit)",
  "Technische Informatik",
  "Technische Konfektionäre/innen, Segelmacher/innen",
  "Technische Mediengestaltung (sonstige Spezialtätigkeit)",
  "Technische Produktionsplanung und -steuerung",
  "Technische Qualitätssicherung",
  "Technische Servicekräfte Wartung und Instandhaltung",
  "Technische Zeichner/innen",
  "Technischer Eisenbahnbetrieb",
  "Technischer Luftverkehrsbetrieb",
  "Technischer Schiffsverkehrsbetrieb",
  "Technisches Zeichnen, Konstruktion und Modellbau (sonstige Spezialtätigkeit)",
  "Textilgestaltung",
  "Textilherstellung",
  "Textilreinigung",
  "Textiltechnik",
  "Textilveredlung",
  "Theater-, Film- und Fernsehproduktion",
  "Theater-, Film- und Fernsehproduktion (sonstige Spezialtätigkeit)",
  "Theologie",
  "Theologie und Gemeindearbeit (sonstige Spezialtätigkeit)",
  "Tiefbau",
  "Tierärzte/-ärztinnen",
  "Tierärzte/-ärztinnen für Groß- und Nutztiere",
  "Tierärzte/-ärztinnen für Haus- und Heimtiere",
  "Tierheilpraktiker/innen",
  "Tiermedizin und Tierheilkunde (sonstige Spezialtätigkeit)",
  "Tiermedizinische Fachangestellte",
  "Tierpflege",
  "Tierpflege (sonstige Spezialtätigkeit)",
  "Tierwirtschaft (sonstige Spezialtätigkeit)",
  "Tourismuskaufleute",
  "Trainer/innen-Ballsportarten",
  "Trainer/innen-Fitness und Gymnastik",
  "Triebfahrzeugführer/innen Eisenbahnverkehr",
  "Überwachung und Steuerung Eisenbahnverkehrsbetrieb",
  "Überwachung und Steuerung Luftverkehrsbetrieb",
  "Überwachung und Steuerung Schiffsverkehrsbetrieb",
  "Überwachung und Steuerung Straßenverkehrsbetrieb",
  "Überwachung und Steuerung Verkehrsbetrieb",
  "Überwachung und Steuerung Verkehrsbetrieb (sonstige Spezialtätigkeit)",
  "Überwachung und Wartung Eisenbahninfrastruktur",
  "Uhrmacherhandwerk",
  "Umweltschutztechnik",
  "Umweltschutztechnik (sonstige Spezialtätigkeit)",
  "Umweltschutzverwaltung und -beratung",
  "Unternehmensberatung",
  "Unternehmensorganisation und -planung",
  "Unternehmensorganisation und -strategie (sonstige Spezialtätigkeit)",
  "Unteroffiziere mit Portepee",
  "Unteroffiziere ohne Portepee",
  "Ver- und Entsorgung",
  "Veranstaltungs- und Bühnentechnik",
  "Veranstaltungsservice und -management",
  "Veranstaltungstechnik, Kamera- und Tontechnik (sonstige Spezialtätigkeit)",
  "Verbraucherberatung",
  "Verfassungsschutz",
  "Vergolderhandwerk",
  "Verkauf (ohne Produktspezialisierung)",
  "Verkauf (ohne Produktspezialisierung) (sonstige Spezialtätigkeit)",
  "Verkauf (sonstige Spezialtätigkeit)",
  "Verkauf Bekleidung, Sportartikel, Lederwaren und Schuhe",
  "Verkauf Bürobedarf, Geschenk- und Spielwaren",
  "Verkauf drogerie- und apothekenübliche Waren",
  "Verkauf Elektro-, Elektronik und Haushaltswaren",
  "Verkauf Garten-, Heimwerker-, Haustier- und Zoobedarf",
  "Verkauf Kraftfahrzeuge, Zweiräder und Zubehör",
  "Verkauf Lebensmittel (sonstige Spezialtätigkeit)",
  "Verkauf Möbel und Einrichtungsgegenstände",
  "Verkauf von Back- und Konditoreiwaren",
  "Verkauf von Fleischwaren",
  "Verkauf von Lebensmitteln",
  "Verkauf von Sanitäts- und Medizinbedarf",
  "Verkauf von Schmuck und Uhren",
  "Verkaufsstand- und Marktverkäufer/innen",
  "Verkehrskaufleute",
  "Verlags- und Medienkaufleute",
  "Verlags- und Medienkaufleute (sonstige Spezialtätigkeit)",
  "Verleih (außer Geld- und Pfandverleih)",
  "Vermessungstechnik",
  "Versicherungs- und Finanzdienstleistungen (sonstige Spezialtätigkeit)",
  "Versicherungskaufleute",
  "Vertrieb (außer Informations- und Kommunikationstechnik)",
  "Verwaltende Berufe Sozial- und Gesundheitswesen",
  "Visuelles Marketing",
  "Vor-, Kalt- und Süßspeisenköche/-köchinnen",
  "Wachszieherei",
  "Wasserstraßen- und Brückenwärter/innen",
  "Wasserversorgungs- und Abwassertechnik",
  "Wasserwirtschaft",
  "Webadministration",
  "Weinbau",
  "Weinküfer/innen",
  "Wellnessberufe",
  "Werbung und Marketing",
  "Werkstofftechnik",
  "Werkzeugtechnik",
  "Wirtschaftsförderung",
  "Wirtschaftsinformatik",
  "Wirtschaftsprüfung",
  "Wirtschaftswissenschaften",
  "Wirtschaftswissenschaften (sonstige Spezialtätigkeit)",
  "Zahnärzte/-innen und Kieferorthopäden/-innen",
  "Zahnmedizinische Fachangestellte",
  "Zahntechnik",
  "Zauberer/-innen und Illusionisten/-innen",
  "Zimmerei",
  "Zolldienst",
  "Zweiradtechnik",
];
