/**
 * Zuordnung jedes THW-Ortsverbands zu Regionalstelle und Landesverband sowie
 * die Kontaktdaten der Regionalstellen und Landesverbände (für das Autofill
 * der Zugehörigkeit-Ebenen 2/3).
 * Schlüssel von THW_OV_REGIONALSTRUKTUR ist der OV-Name aus thw-ov.ts
 * (THW_ORTSVERBAENDE[].name); Schlüssel der Kontakt-Tabellen sind die
 * Regionalstellen- bzw. Landesverbandsnamen aus THW_OV_REGIONALSTRUKTUR.
 *
 * GENERIERT — nicht von Hand bearbeiten.
 * Quelle: https://thwiki.org/api.php (THWiki), abgerufen 2026-07-14.
 * Neu erzeugen mit:  node scripts/ov-regionalstruktur-generieren.mjs
 */

export interface OvRegionalstruktur {
  /** Name der zuständigen Regionalstelle, z. B. "Aachen". */
  regionalstelle: string;
  /** Landesverband (THW-Bezeichnung, ggf. Ländergruppe), z. B. "Bremen, Niedersachsen". */
  landesverband: string;
}

/** Kontaktdaten einer Regionalstelle oder eines Landesverbands. */
export interface StelleKontakt {
  /** Telefon in nationaler Schreibweise, z. B. "0241 920322-0". */
  telefon: string;
  /** Poststellen-E-Mail, z. B. "Poststelle.RSt_Aachen@thw.de". */
  email: string;
}

export const THW_OV_REGIONALSTRUKTUR: Record<string, OvRegionalstruktur> = {
  "Aachen": { regionalstelle: "Aachen", landesverband: "Nordrhein-Westfalen" },
  "Aalen": { regionalstelle: "Göppingen", landesverband: "Baden-Württemberg" },
  "Achern": { regionalstelle: "Freiburg", landesverband: "Baden-Württemberg" },
  "Achim": { regionalstelle: "Verden", landesverband: "Bremen, Niedersachsen" },
  "Adelsheim": { regionalstelle: "Mannheim", landesverband: "Baden-Württemberg" },
  "Ahaus": { regionalstelle: "Wesel", landesverband: "Nordrhein-Westfalen" },
  "Ahrensburg": { regionalstelle: "Lübeck", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Ahrweiler": { regionalstelle: "Koblenz", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Albstadt": { regionalstelle: "Tübingen", landesverband: "Baden-Württemberg" },
  "Alsdorf": { regionalstelle: "Aachen", landesverband: "Nordrhein-Westfalen" },
  "Alsfeld": { regionalstelle: "Gelnhausen", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Altena": { regionalstelle: "Dortmund", landesverband: "Nordrhein-Westfalen" },
  "Altenburg": { regionalstelle: "Leipzig", landesverband: "Sachsen, Thüringen" },
  "Altötting": { regionalstelle: "Mühldorf", landesverband: "Bayern" },
  "Alzenau": { regionalstelle: "Karlstadt", landesverband: "Bayern" },
  "Alzey": { regionalstelle: "Bad Kreuznach", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Amberg": { regionalstelle: "Schwandorf", landesverband: "Bayern" },
  "Andernach": { regionalstelle: "Koblenz", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Annaberg": { regionalstelle: "Chemnitz", landesverband: "Sachsen, Thüringen" },
  "Ansbach": { regionalstelle: "Nürnberg", landesverband: "Bayern" },
  "Apolda": { regionalstelle: "Erfurt", landesverband: "Sachsen, Thüringen" },
  "Arnsberg": { regionalstelle: "Arnsberg", landesverband: "Nordrhein-Westfalen" },
  "Aschaffenburg": { regionalstelle: "Karlstadt", landesverband: "Bayern" },
  "Attendorn": { regionalstelle: "Olpe", landesverband: "Nordrhein-Westfalen" },
  "Aue-Schwarzenberg": { regionalstelle: "Chemnitz", landesverband: "Sachsen, Thüringen" },
  "Augsburg": { regionalstelle: "München", landesverband: "Bayern" },
  "Aurich": { regionalstelle: "Oldenburg", landesverband: "Bremen, Niedersachsen" },
  "Backnang": { regionalstelle: "Stuttgart", landesverband: "Baden-Württemberg" },
  "Bad Aibling": { regionalstelle: "Bad Tölz", landesverband: "Bayern" },
  "Bad Belzig": { regionalstelle: "Potsdam", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Bad Bergzabern": { regionalstelle: "Neustadt a.d.W.", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Bad Berleburg": { regionalstelle: "Olpe", landesverband: "Nordrhein-Westfalen" },
  "Bad Doberan": { regionalstelle: "Schwerin", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Bad Essen": { regionalstelle: "Lingen", landesverband: "Bremen, Niedersachsen" },
  "Bad Hersfeld": { regionalstelle: "Homberg", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Bad Homburg": { regionalstelle: "Frankfurt am Main", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Bad Honnef": { regionalstelle: "Köln", landesverband: "Nordrhein-Westfalen" },
  "Bad Kissingen": { regionalstelle: "Bamberg", landesverband: "Bayern" },
  "Bad Kreuznach": { regionalstelle: "Bad Kreuznach", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Bad Lauterberg": { regionalstelle: "Göttingen", landesverband: "Bremen, Niedersachsen" },
  "Bad Oldesloe": { regionalstelle: "Lübeck", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Bad Orb": { regionalstelle: "Gelnhausen", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Bad Säckingen": { regionalstelle: "Villingen-Schwenningen", landesverband: "Baden-Württemberg" },
  "Bad Segeberg": { regionalstelle: "Neumünster", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Bad Staffelstein": { regionalstelle: "Bamberg", landesverband: "Bayern" },
  "Bad Wildungen": { regionalstelle: "Gießen", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Baden-Baden": { regionalstelle: "Karlsruhe", landesverband: "Baden-Württemberg" },
  "Baiersdorf": { regionalstelle: "Nürnberg", landesverband: "Bayern" },
  "Balingen": { regionalstelle: "Tübingen", landesverband: "Baden-Württemberg" },
  "Balve": { regionalstelle: "Dortmund", landesverband: "Nordrhein-Westfalen" },
  "Bamberg": { regionalstelle: "Bamberg", landesverband: "Bayern" },
  "Barmstedt": { regionalstelle: "Neumünster", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Barth": { regionalstelle: "Stralsund", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Bassum": { regionalstelle: "Verden", landesverband: "Bremen, Niedersachsen" },
  "Bautzen": { regionalstelle: "Dresden", landesverband: "Sachsen, Thüringen" },
  "Bayreuth": { regionalstelle: "Hof", landesverband: "Bayern" },
  "Beckingen": { regionalstelle: "Merzig", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Beckum": { regionalstelle: "Münster", landesverband: "Nordrhein-Westfalen" },
  "Bendorf": { regionalstelle: "Koblenz", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Bensheim": { regionalstelle: "Darmstadt", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Berchtesgadener Land": { regionalstelle: "Mühldorf", landesverband: "Bayern" },
  "Bergen auf Rügen": { regionalstelle: "Stralsund", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Bergheim": { regionalstelle: "Köln", landesverband: "Nordrhein-Westfalen" },
  "Bergisch Gladbach": { regionalstelle: "Köln", landesverband: "Nordrhein-Westfalen" },
  "Bergneustadt": { regionalstelle: "Olpe", landesverband: "Nordrhein-Westfalen" },
  "Berlin Charlottenburg-Wilmersdorf": { regionalstelle: "Berlin", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Berlin Friedrichshain-Kreuzberg": { regionalstelle: "Berlin", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Berlin Lichtenberg": { regionalstelle: "Berlin", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Berlin Marzahn-Hellersdorf": { regionalstelle: "Berlin", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Berlin Neukölln": { regionalstelle: "Berlin", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Berlin Pankow": { regionalstelle: "Berlin", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Berlin Reinickendorf": { regionalstelle: "Berlin", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Berlin Spandau": { regionalstelle: "Berlin", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Berlin Steglitz-Zehlendorf": { regionalstelle: "Potsdam", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Berlin Tempelhof-Schöneberg": { regionalstelle: "Potsdam", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Berlin Treptow-Köpenick": { regionalstelle: "Berlin", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Berlin-Mitte": { regionalstelle: "Berlin", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Bernburg": { regionalstelle: "Magdeburg", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Betzdorf": { regionalstelle: "Koblenz", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Beuel": { regionalstelle: "Köln", landesverband: "Nordrhein-Westfalen" },
  "Biberach/Baden": { regionalstelle: "Freiburg", landesverband: "Baden-Württemberg" },
  "Biberach/Riß": { regionalstelle: "Biberach", landesverband: "Baden-Württemberg" },
  "Biedenkopf": { regionalstelle: "Gießen", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Bielefeld": { regionalstelle: "Bielefeld", landesverband: "Nordrhein-Westfalen" },
  "Bietigheim-Bissingen": { regionalstelle: "Stuttgart", landesverband: "Baden-Württemberg" },
  "Bingen": { regionalstelle: "Bad Kreuznach", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Bitburg": { regionalstelle: "Trier", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Blaubeuren": { regionalstelle: "Biberach", landesverband: "Baden-Württemberg" },
  "Blieskastel-Aßweiler": { regionalstelle: "Saarbrücken", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Böblingen": { regionalstelle: "Stuttgart", landesverband: "Baden-Württemberg" },
  "Bocholt/Borken": { regionalstelle: "Wesel", landesverband: "Nordrhein-Westfalen" },
  "Bochum": { regionalstelle: "Bochum", landesverband: "Nordrhein-Westfalen" },
  "Bogen": { regionalstelle: "Straubing", landesverband: "Bayern" },
  "Bonn": { regionalstelle: "Köln", landesverband: "Nordrhein-Westfalen" },
  "Borna": { regionalstelle: "Leipzig", landesverband: "Sachsen, Thüringen" },
  "Bornheim": { regionalstelle: "Köln", landesverband: "Nordrhein-Westfalen" },
  "Bottrop": { regionalstelle: "Gelsenkirchen", landesverband: "Nordrhein-Westfalen" },
  "Brandenburg an der Havel": { regionalstelle: "Potsdam", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Braunschweig": { regionalstelle: "Braunschweig", landesverband: "Bremen, Niedersachsen" },
  "Breisach": { regionalstelle: "Freiburg", landesverband: "Baden-Württemberg" },
  "Bremen Mitte": { regionalstelle: "Bremen", landesverband: "Bremen, Niedersachsen" },
  "Bremen Nord": { regionalstelle: "Bremen", landesverband: "Bremen, Niedersachsen" },
  "Bremen Ost": { regionalstelle: "Bremen", landesverband: "Bremen, Niedersachsen" },
  "Bremen Süd": { regionalstelle: "Bremen", landesverband: "Bremen, Niedersachsen" },
  "Bremerhaven": { regionalstelle: "Bremen", landesverband: "Bremen, Niedersachsen" },
  "Brilon": { regionalstelle: "Arnsberg", landesverband: "Nordrhein-Westfalen" },
  "Brühl": { regionalstelle: "Köln", landesverband: "Nordrhein-Westfalen" },
  "Bückeburg": { regionalstelle: "Hannover", landesverband: "Bremen, Niedersachsen" },
  "Bühl": { regionalstelle: "Karlsruhe", landesverband: "Baden-Württemberg" },
  "Bünde": { regionalstelle: "Bielefeld", landesverband: "Nordrhein-Westfalen" },
  "Büren": { regionalstelle: "Arnsberg", landesverband: "Nordrhein-Westfalen" },
  "Burg": { regionalstelle: "Magdeburg", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Burg-Hochdonn": { regionalstelle: "Neumünster", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Burgdorf": { regionalstelle: "Hannover", landesverband: "Bremen, Niedersachsen" },
  "Buxtehude": { regionalstelle: "Buxtehude", landesverband: "Bremen, Niedersachsen" },
  "Calbe": { regionalstelle: "Magdeburg", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Calw": { regionalstelle: "Stuttgart", landesverband: "Baden-Württemberg" },
  "Castrop-Rauxel": { regionalstelle: "Gelsenkirchen", landesverband: "Nordrhein-Westfalen" },
  "Celle": { regionalstelle: "Verden", landesverband: "Bremen, Niedersachsen" },
  "Cham": { regionalstelle: "Schwandorf", landesverband: "Bayern" },
  "Chemnitz": { regionalstelle: "Chemnitz", landesverband: "Sachsen, Thüringen" },
  "Clausthal-Zellerfeld": { regionalstelle: "Göttingen", landesverband: "Bremen, Niedersachsen" },
  "Cloppenburg": { regionalstelle: "Lingen", landesverband: "Bremen, Niedersachsen" },
  "Coburg": { regionalstelle: "Bamberg", landesverband: "Bayern" },
  "Cochem": { regionalstelle: "Trier", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Coesfeld": { regionalstelle: "Münster", landesverband: "Nordrhein-Westfalen" },
  "Cottbus": { regionalstelle: "Frankfurt (Oder)", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Crailsheim": { regionalstelle: "Heilbronn", landesverband: "Baden-Württemberg" },
  "Cuxhaven": { regionalstelle: "Bremen", landesverband: "Bremen, Niedersachsen" },
  "Dachau": { regionalstelle: "München", landesverband: "Bayern" },
  "Darmstadt": { regionalstelle: "Darmstadt", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Datteln": { regionalstelle: "Gelsenkirchen", landesverband: "Nordrhein-Westfalen" },
  "Daun-Vulkaneifel": { regionalstelle: "Trier", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Deggendorf": { regionalstelle: "Straubing", landesverband: "Bayern" },
  "Delmenhorst": { regionalstelle: "Bremen", landesverband: "Bremen, Niedersachsen" },
  "Demmin": { regionalstelle: "Stralsund", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Dessau": { regionalstelle: "Halle", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Detmold": { regionalstelle: "Bielefeld", landesverband: "Nordrhein-Westfalen" },
  "Dettenheim": { regionalstelle: "Karlsruhe", landesverband: "Baden-Württemberg" },
  "Dillenburg": { regionalstelle: "Gießen", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Dillingen": { regionalstelle: "Ingolstadt", landesverband: "Bayern" },
  "Dillingen (Saar)": { regionalstelle: "Merzig", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Dinkelsbühl": { regionalstelle: "Nürnberg", landesverband: "Bayern" },
  "Dinslaken": { regionalstelle: "Wesel", landesverband: "Nordrhein-Westfalen" },
  "Dippoldiswalde": { regionalstelle: "Dresden", landesverband: "Sachsen, Thüringen" },
  "Döbeln": { regionalstelle: "Chemnitz", landesverband: "Sachsen, Thüringen" },
  "Donaueschingen": { regionalstelle: "Villingen-Schwenningen", landesverband: "Baden-Württemberg" },
  "Donauwörth": { regionalstelle: "Ingolstadt", landesverband: "Bayern" },
  "Dortmund": { regionalstelle: "Dortmund", landesverband: "Nordrhein-Westfalen" },
  "Dresden": { regionalstelle: "Dresden", landesverband: "Sachsen, Thüringen" },
  "Duisburg": { regionalstelle: "Düsseldorf", landesverband: "Nordrhein-Westfalen" },
  "Dülmen": { regionalstelle: "Münster", landesverband: "Nordrhein-Westfalen" },
  "Düren": { regionalstelle: "Aachen", landesverband: "Nordrhein-Westfalen" },
  "Düsseldorf": { regionalstelle: "Düsseldorf", landesverband: "Nordrhein-Westfalen" },
  "Eberbach": { regionalstelle: "Mannheim", landesverband: "Baden-Württemberg" },
  "Eberswalde": { regionalstelle: "Frankfurt (Oder)", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Eckernförde": { regionalstelle: "Schleswig", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Eggenfelden": { regionalstelle: "Mühldorf", landesverband: "Bayern" },
  "Ehingen": { regionalstelle: "Biberach", landesverband: "Baden-Württemberg" },
  "Eichstätt": { regionalstelle: "Ingolstadt", landesverband: "Bayern" },
  "Eilenburg": { regionalstelle: "Leipzig", landesverband: "Sachsen, Thüringen" },
  "Einbeck": { regionalstelle: "Göttingen", landesverband: "Bremen, Niedersachsen" },
  "Eisenach": { regionalstelle: "Erfurt", landesverband: "Sachsen, Thüringen" },
  "Ellwangen": { regionalstelle: "Göppingen", landesverband: "Baden-Württemberg" },
  "Elmshorn": { regionalstelle: "Neumünster", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Elze": { regionalstelle: "Braunschweig", landesverband: "Bremen, Niedersachsen" },
  "Emden": { regionalstelle: "Oldenburg", landesverband: "Bremen, Niedersachsen" },
  "Emmendingen": { regionalstelle: "Freiburg", landesverband: "Baden-Württemberg" },
  "Emmerich": { regionalstelle: "Wesel", landesverband: "Nordrhein-Westfalen" },
  "Erfurt": { regionalstelle: "Erfurt", landesverband: "Sachsen, Thüringen" },
  "Ergolding": { regionalstelle: "Mühldorf", landesverband: "Bayern" },
  "Erkelenz": { regionalstelle: "Mönchengladbach", landesverband: "Nordrhein-Westfalen" },
  "Erlangen": { regionalstelle: "Nürnberg", landesverband: "Bayern" },
  "Erlensee": { regionalstelle: "Gelnhausen", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Eschwege": { regionalstelle: "Homberg", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Eschweiler": { regionalstelle: "Aachen", landesverband: "Nordrhein-Westfalen" },
  "Essen": { regionalstelle: "Gelsenkirchen", landesverband: "Nordrhein-Westfalen" },
  "Euskirchen": { regionalstelle: "Aachen", landesverband: "Nordrhein-Westfalen" },
  "Eutin": { regionalstelle: "Lübeck", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Fallingbostel-Walsrode": { regionalstelle: "Verden", landesverband: "Bremen, Niedersachsen" },
  "Feuchtwangen": { regionalstelle: "Nürnberg", landesverband: "Bayern" },
  "Flensburg": { regionalstelle: "Schleswig", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Forchheim": { regionalstelle: "Bamberg", landesverband: "Bayern" },
  "Forst (Lausitz)": { regionalstelle: "Frankfurt (Oder)", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Frankenberg": { regionalstelle: "Gießen", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Frankenthal": { regionalstelle: "Bad Kreuznach", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Frankfurt": { regionalstelle: "Frankfurt am Main", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Frankfurt (Oder)": { regionalstelle: "Frankfurt (Oder)", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Freiberg": { regionalstelle: "Chemnitz", landesverband: "Sachsen, Thüringen" },
  "Freiburg": { regionalstelle: "Freiburg", landesverband: "Baden-Württemberg" },
  "Freisen": { regionalstelle: "Merzig", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Freising": { regionalstelle: "München", landesverband: "Bayern" },
  "Freudenstadt": { regionalstelle: "Tübingen", landesverband: "Baden-Württemberg" },
  "Friedberg": { regionalstelle: "München", landesverband: "Bayern" },
  "Friedberg/Hessen": { regionalstelle: "Frankfurt am Main", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Friedrichshafen": { regionalstelle: "Biberach", landesverband: "Baden-Württemberg" },
  "Friedrichsthal": { regionalstelle: "Saarbrücken", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Fritzlar": { regionalstelle: "Homberg", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Fulda": { regionalstelle: "Gelnhausen", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Fürstenfeldbruck": { regionalstelle: "München", landesverband: "Bayern" },
  "Fürstenwalde/Spree": { regionalstelle: "Frankfurt (Oder)", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Fürth": { regionalstelle: "Nürnberg", landesverband: "Bayern" },
  "Füssen": { regionalstelle: "Kempten", landesverband: "Bayern" },
  "Gadebusch": { regionalstelle: "Schwerin", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Garmisch-Partenkirchen": { regionalstelle: "Bad Tölz", landesverband: "Bayern" },
  "Geisenheim": { regionalstelle: "Frankfurt am Main", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Geislingen": { regionalstelle: "Göppingen", landesverband: "Baden-Württemberg" },
  "Geldern": { regionalstelle: "Wesel", landesverband: "Nordrhein-Westfalen" },
  "Gelnhausen": { regionalstelle: "Gelnhausen", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Gelsenkirchen": { regionalstelle: "Gelsenkirchen", landesverband: "Nordrhein-Westfalen" },
  "Gera": { regionalstelle: "Leipzig", landesverband: "Sachsen, Thüringen" },
  "Geretsried": { regionalstelle: "Bad Tölz", landesverband: "Bayern" },
  "Germersheim": { regionalstelle: "Neustadt a.d.W.", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Gerolzhofen": { regionalstelle: "Bamberg", landesverband: "Bayern" },
  "Gieboldehausen": { regionalstelle: "Göttingen", landesverband: "Bremen, Niedersachsen" },
  "Gießen": { regionalstelle: "Gießen", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Gifhorn": { regionalstelle: "Braunschweig", landesverband: "Bremen, Niedersachsen" },
  "Gladbeck/Dorsten": { regionalstelle: "Gelsenkirchen", landesverband: "Nordrhein-Westfalen" },
  "Göppingen": { regionalstelle: "Göppingen", landesverband: "Baden-Württemberg" },
  "Görlitz": { regionalstelle: "Dresden", landesverband: "Sachsen, Thüringen" },
  "Goslar": { regionalstelle: "Göttingen", landesverband: "Bremen, Niedersachsen" },
  "Gotha": { regionalstelle: "Erfurt", landesverband: "Sachsen, Thüringen" },
  "Göttingen": { regionalstelle: "Göttingen", landesverband: "Bremen, Niedersachsen" },
  "Gransee": { regionalstelle: "Potsdam", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Greifswald": { regionalstelle: "Stralsund", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Greven": { regionalstelle: "Münster", landesverband: "Nordrhein-Westfalen" },
  "Grevenbroich": { regionalstelle: "Mönchengladbach", landesverband: "Nordrhein-Westfalen" },
  "Grimma": { regionalstelle: "Leipzig", landesverband: "Sachsen, Thüringen" },
  "Gronau": { regionalstelle: "Wesel", landesverband: "Nordrhein-Westfalen" },
  "Groß-Gerau": { regionalstelle: "Darmstadt", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Groß-Umstadt": { regionalstelle: "Darmstadt", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Großalmerode": { regionalstelle: "Homberg", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Gruibingen": { regionalstelle: "Göppingen", landesverband: "Baden-Württemberg" },
  "Grünberg": { regionalstelle: "Gießen", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Gummersbach": { regionalstelle: "Olpe", landesverband: "Nordrhein-Westfalen" },
  "Günzburg": { regionalstelle: "Kempten", landesverband: "Bayern" },
  "Gunzenhausen": { regionalstelle: "Ingolstadt", landesverband: "Bayern" },
  "Güstrow": { regionalstelle: "Schwerin", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Gütersloh": { regionalstelle: "Bielefeld", landesverband: "Nordrhein-Westfalen" },
  "Haan": { regionalstelle: "Düsseldorf", landesverband: "Nordrhein-Westfalen" },
  "Hagen": { regionalstelle: "Bochum", landesverband: "Nordrhein-Westfalen" },
  "Halberstadt": { regionalstelle: "Magdeburg", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Haldensleben": { regionalstelle: "Magdeburg", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Halle": { regionalstelle: "Bielefeld", landesverband: "Nordrhein-Westfalen" },
  "Halle (Saale)": { regionalstelle: "Halle", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Hallenberg-Hesborn": { regionalstelle: "Arnsberg", landesverband: "Nordrhein-Westfalen" },
  "Haltern am See": { regionalstelle: "Gelsenkirchen", landesverband: "Nordrhein-Westfalen" },
  "Halver": { regionalstelle: "Dortmund", landesverband: "Nordrhein-Westfalen" },
  "Hamburg Mitte": { regionalstelle: "Hamburg", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Hamburg Nord": { regionalstelle: "Hamburg", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Hamburg-Altona": { regionalstelle: "Hamburg", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Hamburg-Bergedorf": { regionalstelle: "Hamburg", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Hamburg-Eimsbüttel": { regionalstelle: "Hamburg", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Hamburg-Harburg": { regionalstelle: "Hamburg", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Hamburg-Wandsbek": { regionalstelle: "Hamburg", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Hameln": { regionalstelle: "Hannover", landesverband: "Bremen, Niedersachsen" },
  "Hamm": { regionalstelle: "Dortmund", landesverband: "Nordrhein-Westfalen" },
  "Hann. Münden": { regionalstelle: "Göttingen", landesverband: "Bremen, Niedersachsen" },
  "Hannover/Langenhagen": { regionalstelle: "Hannover", landesverband: "Bremen, Niedersachsen" },
  "Haßfurt": { regionalstelle: "Bamberg", landesverband: "Bayern" },
  "Haßmersheim": { regionalstelle: "Mannheim", landesverband: "Baden-Württemberg" },
  "Hattingen": { regionalstelle: "Bochum", landesverband: "Nordrhein-Westfalen" },
  "Hauenstein": { regionalstelle: "Neustadt a.d.W.", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Havixbeck": { regionalstelle: "Münster", landesverband: "Nordrhein-Westfalen" },
  "Hechingen": { regionalstelle: "Tübingen", landesverband: "Baden-Württemberg" },
  "Heide": { regionalstelle: "Neumünster", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Heidelberg": { regionalstelle: "Mannheim", landesverband: "Baden-Württemberg" },
  "Heidenheim": { regionalstelle: "Göppingen", landesverband: "Baden-Württemberg" },
  "Heidenrod": { regionalstelle: "Frankfurt am Main", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Heilbronn": { regionalstelle: "Heilbronn", landesverband: "Baden-Württemberg" },
  "Heiligenhaus/Wülfrath": { regionalstelle: "Düsseldorf", landesverband: "Nordrhein-Westfalen" },
  "Heiligenstadt": { regionalstelle: "Erfurt", landesverband: "Sachsen, Thüringen" },
  "Helmstedt": { regionalstelle: "Braunschweig", landesverband: "Bremen, Niedersachsen" },
  "Heppenheim": { regionalstelle: "Darmstadt", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Herford": { regionalstelle: "Bielefeld", landesverband: "Nordrhein-Westfalen" },
  "Hermeskeil": { regionalstelle: "Trier", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Herne": { regionalstelle: "Bochum", landesverband: "Nordrhein-Westfalen" },
  "Herten": { regionalstelle: "Gelsenkirchen", landesverband: "Nordrhein-Westfalen" },
  "Herzberg": { regionalstelle: "Potsdam", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Herzogenrath": { regionalstelle: "Aachen", landesverband: "Nordrhein-Westfalen" },
  "Heusweiler": { regionalstelle: "Saarbrücken", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Hilden": { regionalstelle: "Düsseldorf", landesverband: "Nordrhein-Westfalen" },
  "Hildesheim": { regionalstelle: "Braunschweig", landesverband: "Bremen, Niedersachsen" },
  "Hilpoltstein": { regionalstelle: "Ingolstadt", landesverband: "Bayern" },
  "Hof": { regionalstelle: "Hof", landesverband: "Bayern" },
  "Hofgeismar": { regionalstelle: "Homberg", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Hofheim": { regionalstelle: "Frankfurt am Main", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Holzminden": { regionalstelle: "Göttingen", landesverband: "Bremen, Niedersachsen" },
  "Homberg": { regionalstelle: "Homberg", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Homburg": { regionalstelle: "Saarbrücken", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Horb": { regionalstelle: "Tübingen", landesverband: "Baden-Württemberg" },
  "Höxter": { regionalstelle: "Arnsberg", landesverband: "Nordrhein-Westfalen" },
  "Hoya": { regionalstelle: "Verden", landesverband: "Bremen, Niedersachsen" },
  "Hückelhoven": { regionalstelle: "Mönchengladbach", landesverband: "Nordrhein-Westfalen" },
  "Hückeswagen": { regionalstelle: "Olpe", landesverband: "Nordrhein-Westfalen" },
  "Hude-Bookholzberg": { regionalstelle: "Bremen", landesverband: "Bremen, Niedersachsen" },
  "Hünfeld": { regionalstelle: "Gelnhausen", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Hürtgenwald": { regionalstelle: "Aachen", landesverband: "Nordrhein-Westfalen" },
  "Husum": { regionalstelle: "Schleswig", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Ibbenbüren": { regionalstelle: "Münster", landesverband: "Nordrhein-Westfalen" },
  "Idar-Oberstein": { regionalstelle: "Bad Kreuznach", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Idstein": { regionalstelle: "Frankfurt am Main", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Igersheim": { regionalstelle: "Heilbronn", landesverband: "Baden-Württemberg" },
  "Illingen": { regionalstelle: "Saarbrücken", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Ingolstadt": { regionalstelle: "Ingolstadt", landesverband: "Bayern" },
  "Iserlohn": { regionalstelle: "Dortmund", landesverband: "Nordrhein-Westfalen" },
  "Itzehoe": { regionalstelle: "Neumünster", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Jever": { regionalstelle: "Oldenburg", landesverband: "Bremen, Niedersachsen" },
  "Jülich": { regionalstelle: "Aachen", landesverband: "Nordrhein-Westfalen" },
  "Kaiserslautern": { regionalstelle: "Neustadt a.d.W.", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Kaltenkirchen": { regionalstelle: "Neumünster", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Kamen-Bergkamen": { regionalstelle: "Dortmund", landesverband: "Nordrhein-Westfalen" },
  "Kamenz": { regionalstelle: "Dresden", landesverband: "Sachsen, Thüringen" },
  "Karlsruhe": { regionalstelle: "Karlsruhe", landesverband: "Baden-Württemberg" },
  "Karlstadt": { regionalstelle: "Karlstadt", landesverband: "Bayern" },
  "Kassel": { regionalstelle: "Homberg", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Kaufbeuren": { regionalstelle: "Kempten", landesverband: "Bayern" },
  "Kehl": { regionalstelle: "Freiburg", landesverband: "Baden-Württemberg" },
  "Kelheim": { regionalstelle: "Straubing", landesverband: "Bayern" },
  "Kempen": { regionalstelle: "Mönchengladbach", landesverband: "Nordrhein-Westfalen" },
  "Kempten": { regionalstelle: "Kempten", landesverband: "Bayern" },
  "Kiel": { regionalstelle: "Schleswig", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Kirchehrenbach": { regionalstelle: "Bamberg", landesverband: "Bayern" },
  "Kirchheim/Teck": { regionalstelle: "Göppingen", landesverband: "Baden-Württemberg" },
  "Kitzingen": { regionalstelle: "Karlstadt", landesverband: "Bayern" },
  "Kleve": { regionalstelle: "Wesel", landesverband: "Nordrhein-Westfalen" },
  "Koblenz": { regionalstelle: "Koblenz", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Köln Nord-West": { regionalstelle: "Köln", landesverband: "Nordrhein-Westfalen" },
  "Köln-Ost": { regionalstelle: "Köln", landesverband: "Nordrhein-Westfalen" },
  "Köln-Porz": { regionalstelle: "Köln", landesverband: "Nordrhein-Westfalen" },
  "Konstanz": { regionalstelle: "Villingen-Schwenningen", landesverband: "Baden-Württemberg" },
  "Korbach": { regionalstelle: "Gießen", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Krefeld": { regionalstelle: "Mönchengladbach", landesverband: "Nordrhein-Westfalen" },
  "Kronach": { regionalstelle: "Hof", landesverband: "Bayern" },
  "Krumbach": { regionalstelle: "Kempten", landesverband: "Bayern" },
  "Kulmbach": { regionalstelle: "Hof", landesverband: "Bayern" },
  "Künzelsau": { regionalstelle: "Heilbronn", landesverband: "Baden-Württemberg" },
  "Kutenholz": { regionalstelle: "Buxtehude", landesverband: "Bremen, Niedersachsen" },
  "Laaber": { regionalstelle: "Straubing", landesverband: "Bayern" },
  "Ladenburg": { regionalstelle: "Mannheim", landesverband: "Baden-Württemberg" },
  "Lahnstein": { regionalstelle: "Koblenz", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Lahr": { regionalstelle: "Freiburg", landesverband: "Baden-Württemberg" },
  "Lampertheim": { regionalstelle: "Darmstadt", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Landau": { regionalstelle: "Neustadt a.d.W.", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Landsberg": { regionalstelle: "Bad Tölz", landesverband: "Bayern" },
  "Landshut": { regionalstelle: "Mühldorf", landesverband: "Bayern" },
  "Lauenburg": { regionalstelle: "Lübeck", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Lauf": { regionalstelle: "Schwandorf", landesverband: "Bayern" },
  "Laufenburg": { regionalstelle: "Villingen-Schwenningen", landesverband: "Baden-Württemberg" },
  "Lauterbach": { regionalstelle: "Gelnhausen", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Lebach": { regionalstelle: "Merzig", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Leer": { regionalstelle: "Oldenburg", landesverband: "Bremen, Niedersachsen" },
  "Lehrte": { regionalstelle: "Hannover", landesverband: "Bremen, Niedersachsen" },
  "Leipzig": { regionalstelle: "Leipzig", landesverband: "Sachsen, Thüringen" },
  "Lemgo": { regionalstelle: "Bielefeld", landesverband: "Nordrhein-Westfalen" },
  "Lengerich": { regionalstelle: "Münster", landesverband: "Nordrhein-Westfalen" },
  "Lennestadt": { regionalstelle: "Olpe", landesverband: "Nordrhein-Westfalen" },
  "Leonberg": { regionalstelle: "Stuttgart", landesverband: "Baden-Württemberg" },
  "Leverkusen": { regionalstelle: "Köln", landesverband: "Nordrhein-Westfalen" },
  "Limburg": { regionalstelle: "Gießen", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Lindau": { regionalstelle: "Kempten", landesverband: "Bayern" },
  "Lindenberg": { regionalstelle: "Kempten", landesverband: "Bayern" },
  "Lingen": { regionalstelle: "Lingen", landesverband: "Bremen, Niedersachsen" },
  "Lippstadt": { regionalstelle: "Arnsberg", landesverband: "Nordrhein-Westfalen" },
  "Lohne": { regionalstelle: "Lingen", landesverband: "Bremen, Niedersachsen" },
  "Lohr": { regionalstelle: "Karlstadt", landesverband: "Bayern" },
  "Lörrach": { regionalstelle: "Freiburg", landesverband: "Baden-Württemberg" },
  "Lübbecke": { regionalstelle: "Bielefeld", landesverband: "Nordrhein-Westfalen" },
  "Lübben (Spreewald)": { regionalstelle: "Frankfurt (Oder)", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Lübeck": { regionalstelle: "Lübeck", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Lüchow-Dannenberg": { regionalstelle: "Buxtehude", landesverband: "Bremen, Niedersachsen" },
  "Luckenwalde": { regionalstelle: "Potsdam", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Lüdenscheid": { regionalstelle: "Dortmund", landesverband: "Nordrhein-Westfalen" },
  "Lüdinghausen": { regionalstelle: "Münster", landesverband: "Nordrhein-Westfalen" },
  "Ludwigsburg": { regionalstelle: "Stuttgart", landesverband: "Baden-Württemberg" },
  "Ludwigshafen": { regionalstelle: "Bad Kreuznach", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Ludwigslust": { regionalstelle: "Schwerin", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Lüneburg": { regionalstelle: "Buxtehude", landesverband: "Bremen, Niedersachsen" },
  "Lünen": { regionalstelle: "Dortmund", landesverband: "Nordrhein-Westfalen" },
  "Magdeburg": { regionalstelle: "Magdeburg", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Mainz": { regionalstelle: "Bad Kreuznach", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Mallersdorf": { regionalstelle: "Straubing", landesverband: "Bayern" },
  "Mannheim": { regionalstelle: "Mannheim", landesverband: "Baden-Württemberg" },
  "Marburg": { regionalstelle: "Gießen", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Markt Schwaben": { regionalstelle: "München", landesverband: "Bayern" },
  "Marktheidenfeld": { regionalstelle: "Karlstadt", landesverband: "Bayern" },
  "Marktredwitz": { regionalstelle: "Hof", landesverband: "Bayern" },
  "Marl": { regionalstelle: "Gelsenkirchen", landesverband: "Nordrhein-Westfalen" },
  "Mayen": { regionalstelle: "Koblenz", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Meldorf": { regionalstelle: "Neumünster", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Melle": { regionalstelle: "Lingen", landesverband: "Bremen, Niedersachsen" },
  "Mellrichstadt": { regionalstelle: "Bamberg", landesverband: "Bayern" },
  "Melsungen": { regionalstelle: "Homberg", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Memmingen": { regionalstelle: "Kempten", landesverband: "Bayern" },
  "Meppen": { regionalstelle: "Lingen", landesverband: "Bremen, Niedersachsen" },
  "Merseburg": { regionalstelle: "Halle", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Meschede": { regionalstelle: "Arnsberg", landesverband: "Nordrhein-Westfalen" },
  "Mettlach": { regionalstelle: "Merzig", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Michelstadt": { regionalstelle: "Darmstadt", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Miesbach": { regionalstelle: "Bad Tölz", landesverband: "Bayern" },
  "Miltenberg": { regionalstelle: "Karlstadt", landesverband: "Bayern" },
  "Minden": { regionalstelle: "Bielefeld", landesverband: "Nordrhein-Westfalen" },
  "Moers": { regionalstelle: "Wesel", landesverband: "Nordrhein-Westfalen" },
  "Mölln": { regionalstelle: "Lübeck", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Mönchengladbach": { regionalstelle: "Mönchengladbach", landesverband: "Nordrhein-Westfalen" },
  "Montabaur": { regionalstelle: "Koblenz", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Mühlacker": { regionalstelle: "Karlsruhe", landesverband: "Baden-Württemberg" },
  "Mühldorf": { regionalstelle: "Mühldorf", landesverband: "Bayern" },
  "Mülheim": { regionalstelle: "Düsseldorf", landesverband: "Nordrhein-Westfalen" },
  "Müllheim": { regionalstelle: "Freiburg", landesverband: "Baden-Württemberg" },
  "München-Land": { regionalstelle: "München", landesverband: "Bayern" },
  "München-Mitte": { regionalstelle: "München", landesverband: "Bayern" },
  "München-Ost": { regionalstelle: "München", landesverband: "Bayern" },
  "München-West": { regionalstelle: "München", landesverband: "Bayern" },
  "Münsingen": { regionalstelle: "Tübingen", landesverband: "Baden-Württemberg" },
  "Münster": { regionalstelle: "Münster", landesverband: "Nordrhein-Westfalen" },
  "Nabburg": { regionalstelle: "Schwandorf", landesverband: "Bayern" },
  "Naila": { regionalstelle: "Hof", landesverband: "Bayern" },
  "Naumburg": { regionalstelle: "Halle", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Neckargemünd": { regionalstelle: "Mannheim", landesverband: "Baden-Württemberg" },
  "Nettetal": { regionalstelle: "Mönchengladbach", landesverband: "Nordrhein-Westfalen" },
  "Neu-Isenburg": { regionalstelle: "Frankfurt am Main", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Neu-Ulm": { regionalstelle: "Kempten", landesverband: "Bayern" },
  "Neubrandenburg": { regionalstelle: "Stralsund", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Neuburg": { regionalstelle: "Ingolstadt", landesverband: "Bayern" },
  "Neuenbürg-Arnbach": { regionalstelle: "Karlsruhe", landesverband: "Baden-Württemberg" },
  "Neuhausen": { regionalstelle: "Göppingen", landesverband: "Baden-Württemberg" },
  "Neuhof": { regionalstelle: "Gelnhausen", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Neumarkt": { regionalstelle: "Schwandorf", landesverband: "Bayern" },
  "Neumünster": { regionalstelle: "Neumünster", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Neunburg vorm Wald": { regionalstelle: "Schwandorf", landesverband: "Bayern" },
  "Neunkirchen": { regionalstelle: "Mannheim", landesverband: "Baden-Württemberg" },
  "Neunkirchen (Saar)": { regionalstelle: "Saarbrücken", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Neuruppin": { regionalstelle: "Potsdam", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Neuss": { regionalstelle: "Mönchengladbach", landesverband: "Nordrhein-Westfalen" },
  "Neustadt": { regionalstelle: "Lübeck", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Neustadt an der Aisch": { regionalstelle: "Nürnberg", landesverband: "Bayern" },
  "Neustadt an der Weinstraße": { regionalstelle: "Neustadt a.d.W.", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Neustrelitz": { regionalstelle: "Stralsund", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Neuwied": { regionalstelle: "Koblenz", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Niebüll": { regionalstelle: "Schleswig", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Niefern-Öschelbronn": { regionalstelle: "Karlsruhe", landesverband: "Baden-Württemberg" },
  "Nienburg": { regionalstelle: "Verden", landesverband: "Bremen, Niedersachsen" },
  "Nohfelden": { regionalstelle: "Merzig", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Norden": { regionalstelle: "Oldenburg", landesverband: "Bremen, Niedersachsen" },
  "Nordenham": { regionalstelle: "Oldenburg", landesverband: "Bremen, Niedersachsen" },
  "Norderstedt": { regionalstelle: "Neumünster", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Nordhausen": { regionalstelle: "Erfurt", landesverband: "Sachsen, Thüringen" },
  "Nordhorn": { regionalstelle: "Lingen", landesverband: "Bremen, Niedersachsen" },
  "Nördlingen": { regionalstelle: "Ingolstadt", landesverband: "Bayern" },
  "Northeim": { regionalstelle: "Göttingen", landesverband: "Bremen, Niedersachsen" },
  "Nörvenich": { regionalstelle: "Aachen", landesverband: "Nordrhein-Westfalen" },
  "Nürnberg": { regionalstelle: "Nürnberg", landesverband: "Bayern" },
  "Ober-Ramstadt": { regionalstelle: "Darmstadt", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Oberhausen": { regionalstelle: "Wesel", landesverband: "Nordrhein-Westfalen" },
  "Oberhausen-Rheinhausen": { regionalstelle: "Karlsruhe", landesverband: "Baden-Württemberg" },
  "Obernburg": { regionalstelle: "Karlstadt", landesverband: "Bayern" },
  "Oberviechtach": { regionalstelle: "Schwandorf", landesverband: "Bayern" },
  "Ochsenfurt": { regionalstelle: "Karlstadt", landesverband: "Bayern" },
  "Oelde": { regionalstelle: "Münster", landesverband: "Nordrhein-Westfalen" },
  "Offenbach": { regionalstelle: "Frankfurt am Main", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Offenburg": { regionalstelle: "Freiburg", landesverband: "Baden-Württemberg" },
  "Ofterdingen": { regionalstelle: "Tübingen", landesverband: "Baden-Württemberg" },
  "Oldenburg (NI)": { regionalstelle: "Oldenburg", landesverband: "Bremen, Niedersachsen" },
  "Oldenburg in Holstein": { regionalstelle: "Lübeck", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Olpe": { regionalstelle: "Olpe", landesverband: "Nordrhein-Westfalen" },
  "Oschersleben": { regionalstelle: "Magdeburg", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Osnabrück": { regionalstelle: "Lingen", landesverband: "Bremen, Niedersachsen" },
  "Osterholz-Scharmbeck": { regionalstelle: "Bremen", landesverband: "Bremen, Niedersachsen" },
  "Osterode - NI": { regionalstelle: "Göttingen", landesverband: "Bremen, Niedersachsen" },
  "Ostfildern": { regionalstelle: "Göppingen", landesverband: "Baden-Württemberg" },
  "Paderborn": { regionalstelle: "Arnsberg", landesverband: "Nordrhein-Westfalen" },
  "Papenburg": { regionalstelle: "Lingen", landesverband: "Bremen, Niedersachsen" },
  "Parchim": { regionalstelle: "Schwerin", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Parsberg": { regionalstelle: "Schwandorf", landesverband: "Bayern" },
  "Pasewalk": { regionalstelle: "Stralsund", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Passau": { regionalstelle: "Straubing", landesverband: "Bayern" },
  "Pegnitz": { regionalstelle: "Hof", landesverband: "Bayern" },
  "Peine": { regionalstelle: "Braunschweig", landesverband: "Bremen, Niedersachsen" },
  "Perl-Obermosel": { regionalstelle: "Merzig", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Pfaffenhofen": { regionalstelle: "Ingolstadt", landesverband: "Bayern" },
  "Pfedelbach": { regionalstelle: "Heilbronn", landesverband: "Baden-Württemberg" },
  "Pforzheim": { regionalstelle: "Karlsruhe", landesverband: "Baden-Württemberg" },
  "Pfullendorf": { regionalstelle: "Biberach", landesverband: "Baden-Württemberg" },
  "Pfungstadt": { regionalstelle: "Darmstadt", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Pinneberg": { regionalstelle: "Neumünster", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Pirmasens": { regionalstelle: "Neustadt a.d.W.", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Pirna": { regionalstelle: "Dresden", landesverband: "Sachsen, Thüringen" },
  "Plauen": { regionalstelle: "Chemnitz", landesverband: "Sachsen, Thüringen" },
  "Plön": { regionalstelle: "Lübeck", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Potsdam": { regionalstelle: "Potsdam", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Preetz": { regionalstelle: "Lübeck", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Prenzlau": { regionalstelle: "Frankfurt (Oder)", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Prüm": { regionalstelle: "Trier", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Quakenbrück": { regionalstelle: "Lingen", landesverband: "Bremen, Niedersachsen" },
  "Quedlinburg": { regionalstelle: "Magdeburg", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Radebeul": { regionalstelle: "Dresden", landesverband: "Sachsen, Thüringen" },
  "Radolfzell": { regionalstelle: "Villingen-Schwenningen", landesverband: "Baden-Württemberg" },
  "Rastatt": { regionalstelle: "Karlsruhe", landesverband: "Baden-Württemberg" },
  "Rathenow": { regionalstelle: "Potsdam", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Ratingen": { regionalstelle: "Düsseldorf", landesverband: "Nordrhein-Westfalen" },
  "Ratzeburg": { regionalstelle: "Lübeck", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Recklinghausen": { regionalstelle: "Gelsenkirchen", landesverband: "Nordrhein-Westfalen" },
  "Regen": { regionalstelle: "Straubing", landesverband: "Bayern" },
  "Regensburg": { regionalstelle: "Straubing", landesverband: "Bayern" },
  "Reichenbach": { regionalstelle: "Chemnitz", landesverband: "Sachsen, Thüringen" },
  "Remscheid": { regionalstelle: "Bochum", landesverband: "Nordrhein-Westfalen" },
  "Rendsburg": { regionalstelle: "Schleswig", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Reutlingen": { regionalstelle: "Tübingen", landesverband: "Baden-Württemberg" },
  "Rheine": { regionalstelle: "Münster", landesverband: "Nordrhein-Westfalen" },
  "Rheinfelden": { regionalstelle: "Freiburg", landesverband: "Baden-Württemberg" },
  "Riedlingen": { regionalstelle: "Biberach", landesverband: "Baden-Württemberg" },
  "Riegelsberg": { regionalstelle: "Saarbrücken", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Riesa": { regionalstelle: "Dresden", landesverband: "Sachsen, Thüringen" },
  "Rinteln": { regionalstelle: "Hannover", landesverband: "Bremen, Niedersachsen" },
  "Roding": { regionalstelle: "Schwandorf", landesverband: "Bayern" },
  "Ronnenberg": { regionalstelle: "Hannover", landesverband: "Bremen, Niedersachsen" },
  "Rosenheim": { regionalstelle: "Bad Tölz", landesverband: "Bayern" },
  "Rostock": { regionalstelle: "Schwerin", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Rotenburg": { regionalstelle: "Buxtehude", landesverband: "Bremen, Niedersachsen" },
  "Rotenburg - HE": { regionalstelle: "Homberg", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Roth": { regionalstelle: "Ingolstadt", landesverband: "Bayern" },
  "Rothenburg": { regionalstelle: "Nürnberg", landesverband: "Bayern" },
  "Rottenburg": { regionalstelle: "Tübingen", landesverband: "Baden-Württemberg" },
  "Rottweil": { regionalstelle: "Villingen-Schwenningen", landesverband: "Baden-Württemberg" },
  "Rudolstadt/Saalfeld": { regionalstelle: "Erfurt", landesverband: "Sachsen, Thüringen" },
  "Rüsselsheim": { regionalstelle: "Darmstadt", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Saarbrücken": { regionalstelle: "Saarbrücken", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Saarburg": { regionalstelle: "Trier", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Saarlouis": { regionalstelle: "Merzig", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Saarwellingen": { regionalstelle: "Merzig", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Salzgitter": { regionalstelle: "Braunschweig", landesverband: "Bremen, Niedersachsen" },
  "Salzwedel": { regionalstelle: "Magdeburg", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Sangerhausen": { regionalstelle: "Halle", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Sarstedt": { regionalstelle: "Braunschweig", landesverband: "Bremen, Niedersachsen" },
  "Schleiden": { regionalstelle: "Aachen", landesverband: "Nordrhein-Westfalen" },
  "Schleswig": { regionalstelle: "Schleswig", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Schongau": { regionalstelle: "Bad Tölz", landesverband: "Bayern" },
  "Schöningen": { regionalstelle: "Braunschweig", landesverband: "Bremen, Niedersachsen" },
  "Schopfheim": { regionalstelle: "Freiburg", landesverband: "Baden-Württemberg" },
  "Schorndorf": { regionalstelle: "Stuttgart", landesverband: "Baden-Württemberg" },
  "Schramberg": { regionalstelle: "Villingen-Schwenningen", landesverband: "Baden-Württemberg" },
  "Schwabach": { regionalstelle: "Nürnberg", landesverband: "Bayern" },
  "Schwäbisch Gmünd": { regionalstelle: "Göppingen", landesverband: "Baden-Württemberg" },
  "Schwäbisch Hall": { regionalstelle: "Heilbronn", landesverband: "Baden-Württemberg" },
  "Schwabmünchen": { regionalstelle: "München", landesverband: "Bayern" },
  "Schwalmstadt": { regionalstelle: "Homberg", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Schwandorf": { regionalstelle: "Schwandorf", landesverband: "Bayern" },
  "Schweinfurt": { regionalstelle: "Bamberg", landesverband: "Bayern" },
  "Schwelm": { regionalstelle: "Bochum", landesverband: "Nordrhein-Westfalen" },
  "Schwerin": { regionalstelle: "Schwerin", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Seelow": { regionalstelle: "Frankfurt (Oder)", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Selb": { regionalstelle: "Hof", landesverband: "Bayern" },
  "Seligenstadt": { regionalstelle: "Frankfurt am Main", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Senftenberg": { regionalstelle: "Frankfurt (Oder)", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Siegburg": { regionalstelle: "Köln", landesverband: "Nordrhein-Westfalen" },
  "Siegen": { regionalstelle: "Olpe", landesverband: "Nordrhein-Westfalen" },
  "Simbach": { regionalstelle: "Mühldorf", landesverband: "Bayern" },
  "Simmerath": { regionalstelle: "Aachen", landesverband: "Nordrhein-Westfalen" },
  "Simmern": { regionalstelle: "Bad Kreuznach", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Singen": { regionalstelle: "Villingen-Schwenningen", landesverband: "Baden-Württemberg" },
  "Sinsheim": { regionalstelle: "Mannheim", landesverband: "Baden-Württemberg" },
  "Sinzig": { regionalstelle: "Koblenz", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Soest": { regionalstelle: "Arnsberg", landesverband: "Nordrhein-Westfalen" },
  "Solingen": { regionalstelle: "Düsseldorf", landesverband: "Nordrhein-Westfalen" },
  "Soltau": { regionalstelle: "Verden", landesverband: "Bremen, Niedersachsen" },
  "Sondershausen": { regionalstelle: "Erfurt", landesverband: "Sachsen, Thüringen" },
  "Sonneberg": { regionalstelle: "Erfurt", landesverband: "Sachsen, Thüringen" },
  "Sonthofen": { regionalstelle: "Kempten", landesverband: "Bayern" },
  "Sörup": { regionalstelle: "Schleswig", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Speyer": { regionalstelle: "Neustadt a.d.W.", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Spiesen-Elversberg": { regionalstelle: "Saarbrücken", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Springe": { regionalstelle: "Hannover", landesverband: "Bremen, Niedersachsen" },
  "St. Ingbert": { regionalstelle: "Saarbrücken", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "St. Wendel": { regionalstelle: "Merzig", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Stade": { regionalstelle: "Buxtehude", landesverband: "Bremen, Niedersachsen" },
  "Stadthagen": { regionalstelle: "Hannover", landesverband: "Bremen, Niedersachsen" },
  "Starnberg": { regionalstelle: "Bad Tölz", landesverband: "Bayern" },
  "Staßfurt": { regionalstelle: "Magdeburg", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Steinau": { regionalstelle: "Gelnhausen", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Stelle-Winsen": { regionalstelle: "Buxtehude", landesverband: "Bremen, Niedersachsen" },
  "Stendal": { regionalstelle: "Magdeburg", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Stockach": { regionalstelle: "Villingen-Schwenningen", landesverband: "Baden-Württemberg" },
  "Stolberg": { regionalstelle: "Aachen", landesverband: "Nordrhein-Westfalen" },
  "Stralsund": { regionalstelle: "Stralsund", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Straubing": { regionalstelle: "Straubing", landesverband: "Bayern" },
  "Stuttgart": { regionalstelle: "Stuttgart", landesverband: "Baden-Württemberg" },
  "Stützpunkt Louisenlund": { regionalstelle: "Schleswig", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Suhl": { regionalstelle: "Erfurt", landesverband: "Sachsen, Thüringen" },
  "Sulingen": { regionalstelle: "Verden", landesverband: "Bremen, Niedersachsen" },
  "Sulzbach": { regionalstelle: "Saarbrücken", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Sulzbach-Rosenberg": { regionalstelle: "Schwandorf", landesverband: "Bayern" },
  "Syke": { regionalstelle: "Verden", landesverband: "Bremen, Niedersachsen" },
  "Theley": { regionalstelle: "Merzig", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Tönning": { regionalstelle: "Schleswig", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Torgau": { regionalstelle: "Leipzig", landesverband: "Sachsen, Thüringen" },
  "Traunreut": { regionalstelle: "Mühldorf", landesverband: "Bayern" },
  "Traunstein": { regionalstelle: "Mühldorf", landesverband: "Bayern" },
  "Treuchtlingen": { regionalstelle: "Ingolstadt", landesverband: "Bayern" },
  "Trier": { regionalstelle: "Trier", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Trossingen": { regionalstelle: "Villingen-Schwenningen", landesverband: "Baden-Württemberg" },
  "Tübingen": { regionalstelle: "Tübingen", landesverband: "Baden-Württemberg" },
  "Tuttlingen": { regionalstelle: "Villingen-Schwenningen", landesverband: "Baden-Württemberg" },
  "Übach-Palenberg": { regionalstelle: "Mönchengladbach", landesverband: "Nordrhein-Westfalen" },
  "Überlingen": { regionalstelle: "Biberach", landesverband: "Baden-Württemberg" },
  "Uelzen": { regionalstelle: "Buxtehude", landesverband: "Bremen, Niedersachsen" },
  "Ulm": { regionalstelle: "Biberach", landesverband: "Baden-Württemberg" },
  "Unna-Schwerte": { regionalstelle: "Dortmund", landesverband: "Nordrhein-Westfalen" },
  "Varel": { regionalstelle: "Oldenburg", landesverband: "Bremen, Niedersachsen" },
  "Velbert": { regionalstelle: "Düsseldorf", landesverband: "Nordrhein-Westfalen" },
  "Verden": { regionalstelle: "Verden", landesverband: "Bremen, Niedersachsen" },
  "Viernheim": { regionalstelle: "Darmstadt", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Viersen": { regionalstelle: "Mönchengladbach", landesverband: "Nordrhein-Westfalen" },
  "Villingen-Schwenningen": { regionalstelle: "Villingen-Schwenningen", landesverband: "Baden-Württemberg" },
  "Vilshofen": { regionalstelle: "Straubing", landesverband: "Bayern" },
  "Vlotho": { regionalstelle: "Bielefeld", landesverband: "Nordrhein-Westfalen" },
  "Völklingen-Püttlingen": { regionalstelle: "Saarbrücken", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Wächtersbach": { regionalstelle: "Gelnhausen", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Wadern": { regionalstelle: "Merzig", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Waghäusel": { regionalstelle: "Karlsruhe", landesverband: "Baden-Württemberg" },
  "Wahlstedt": { regionalstelle: "Neumünster", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Waldbröl": { regionalstelle: "Olpe", landesverband: "Nordrhein-Westfalen" },
  "Waldshut-Tiengen": { regionalstelle: "Villingen-Schwenningen", landesverband: "Baden-Württemberg" },
  "Waltrop": { regionalstelle: "Gelsenkirchen", landesverband: "Nordrhein-Westfalen" },
  "Wangen": { regionalstelle: "Biberach", landesverband: "Baden-Württemberg" },
  "Wanne-Eickel": { regionalstelle: "Bochum", landesverband: "Nordrhein-Westfalen" },
  "Warburg": { regionalstelle: "Arnsberg", landesverband: "Nordrhein-Westfalen" },
  "Wardenburg": { regionalstelle: "Bremen", landesverband: "Bremen, Niedersachsen" },
  "Waren": { regionalstelle: "Stralsund", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Warendorf": { regionalstelle: "Münster", landesverband: "Nordrhein-Westfalen" },
  "Weiden": { regionalstelle: "Hof", landesverband: "Bayern" },
  "Weilburg": { regionalstelle: "Gießen", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Weilheim": { regionalstelle: "Bad Tölz", landesverband: "Bayern" },
  "Weingarten": { regionalstelle: "Biberach", landesverband: "Baden-Württemberg" },
  "Weinsberg": { regionalstelle: "Heilbronn", landesverband: "Baden-Württemberg" },
  "Weißenfels": { regionalstelle: "Halle", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Wermelskirchen": { regionalstelle: "Olpe", landesverband: "Nordrhein-Westfalen" },
  "Werne": { regionalstelle: "Dortmund", landesverband: "Nordrhein-Westfalen" },
  "Wertheim": { regionalstelle: "Heilbronn", landesverband: "Baden-Württemberg" },
  "Wesel": { regionalstelle: "Wesel", landesverband: "Nordrhein-Westfalen" },
  "Westerburg": { regionalstelle: "Koblenz", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Westerstede": { regionalstelle: "Oldenburg", landesverband: "Bremen, Niedersachsen" },
  "Wetter": { regionalstelle: "Bochum", landesverband: "Nordrhein-Westfalen" },
  "Wetzlar": { regionalstelle: "Gießen", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Widdern": { regionalstelle: "Heilbronn", landesverband: "Baden-Württemberg" },
  "Wiesbaden": { regionalstelle: "Frankfurt am Main", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Wiesloch-Walldorf": { regionalstelle: "Mannheim", landesverband: "Baden-Württemberg" },
  "Wilhelmshaven": { regionalstelle: "Oldenburg", landesverband: "Bremen, Niedersachsen" },
  "Wismar": { regionalstelle: "Schwerin", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Witten": { regionalstelle: "Bochum", landesverband: "Nordrhein-Westfalen" },
  "Wittenberg": { regionalstelle: "Halle", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Wittenberge": { regionalstelle: "Potsdam", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Wittlich": { regionalstelle: "Trier", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Witzenhausen": { regionalstelle: "Homberg", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Wolfen-Bitterfeld": { regionalstelle: "Halle", landesverband: "Berlin, Brandenburg, Sachsen-Anhalt" },
  "Wolfenbüttel": { regionalstelle: "Braunschweig", landesverband: "Bremen, Niedersachsen" },
  "Wolfhagen": { regionalstelle: "Homberg", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Wolfsburg": { regionalstelle: "Braunschweig", landesverband: "Bremen, Niedersachsen" },
  "Wolgast": { regionalstelle: "Stralsund", landesverband: "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein" },
  "Worms": { regionalstelle: "Bad Kreuznach", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Wörrstadt": { regionalstelle: "Bad Kreuznach", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Wörth": { regionalstelle: "Straubing", landesverband: "Bayern" },
  "Wunstorf": { regionalstelle: "Hannover", landesverband: "Bremen, Niedersachsen" },
  "Wuppertal": { regionalstelle: "Bochum", landesverband: "Nordrhein-Westfalen" },
  "Würzburg": { regionalstelle: "Karlstadt", landesverband: "Bayern" },
  "Zell": { regionalstelle: "Trier", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Zittau": { regionalstelle: "Dresden", landesverband: "Sachsen, Thüringen" },
  "Zweibrücken": { regionalstelle: "Neustadt a.d.W.", landesverband: "Hessen, Rheinland-Pfalz, Saarland" },
  "Zwickau": { regionalstelle: "Chemnitz", landesverband: "Sachsen, Thüringen" },
};

/** Regionalstellenname → Kontaktdaten. */
export const THW_REGIONALSTELLEN_KONTAKT: Record<string, StelleKontakt> = {
  "Aachen": { telefon: "0241 920322-0", email: "Poststelle.RSt_Aachen@thw.de" },
  "Arnsberg": { telefon: "02931 9609-0", email: "Poststelle.RSt_Arnsberg@thw.de" },
  "Bad Kreuznach": { telefon: "0671 483546 0", email: "Poststelle.RSt_Bad-Kreuznach@thw.de" },
  "Bad Tölz": { telefon: "08041 79246-0", email: "Poststelle.RSt_Bad-Toelz@thw.de" },
  "Bamberg": { telefon: "09544 98604-0", email: "Poststelle.RSt_Bamberg@thw.de" },
  "Berlin": { telefon: "030 6341467-0", email: "Poststelle.RSt_Berlin@thw.de" },
  "Biberach": { telefon: "0228 9945221-0", email: "Poststelle.RSt_Biberach@thw.de" },
  "Bielefeld": { telefon: "0521 915135-0", email: "Poststelle.RSt_Bielefeld@thw.de" },
  "Bochum": { telefon: "0234 610289-0", email: "Poststelle.RSt_Bochum@thw.de" },
  "Braunschweig": { telefon: "0531 288770-0", email: "Poststelle.RSt_Braunschweig@thw.de" },
  "Bremen": { telefon: "0421 6436230-0", email: "Poststelle.RSt_Bremen@thw.de" },
  "Buxtehude": { telefon: "04161 74960-0", email: "Poststelle.RSt_Buxtehude@thw.de" },
  "Chemnitz": { telefon: "0371 356359 0", email: "Poststelle.Rst_Chemnitz@thw.de" },
  "Darmstadt": { telefon: "06151 30875 0", email: "Poststelle.RSt_Darmstadt@thw.de" },
  "Dortmund": { telefon: "0231 534255-0", email: "Poststelle.RSt_Dortmund@thw.de" },
  "Dresden": { telefon: "0351 563492 0", email: "Poststelle.Rst_Dresden@thw.de" },
  "Düsseldorf": { telefon: "02103 79105-0", email: "Poststelle.RSt_Duesseldorf@thw.de" },
  "Erfurt": { telefon: "0361 601479 0", email: "Poststelle.RSt_Erfurt@thw.de" },
  "Frankfurt (Oder)": { telefon: "0335 284683-0", email: "Poststelle.Rst_Frankfurt_O@thw.de" },
  "Frankfurt am Main": { telefon: "069 7137688 0", email: "Poststelle.RSt_Frankfurt_M@thw.de" },
  "Freiburg": { telefon: "0761 503907-0", email: "Poststelle.RSt_Freiburg@thw.de" },
  "Gelnhausen": { telefon: "06051 91444-0", email: "Poststelle.RSt_Gelnhausen@thw.de" },
  "Gelsenkirchen": { telefon: "0209 386467-0", email: "Poststelle.RSt_Gelsenkirchen@thw.de" },
  "Gießen": { telefon: "06403 97706-0", email: "Poststelle.RSt_Giessen@thw.de" },
  "Göppingen": { telefon: "0228 9945223-0", email: "Poststelle.RSt_Goeppingen@thw.de" },
  "Göttingen": { telefon: "0551 900336-0", email: "Poststelle.RSt_Goettingen@thw.de" },
  "Halle": { telefon: "0345 131613 0", email: "Poststelle.Rst_Halle_Sa@thw.de" },
  "Hamburg": { telefon: "040 5009109-0", email: "Poststelle.RSt_Hamburg@thw.de" },
  "Hannover": { telefon: "0511 6766988-0", email: "Poststelle.RSt_Hannover@thw.de" },
  "Heilbronn": { telefon: "07131 64475-0", email: "Poststelle.RSt_Heilbronn@thw.de" },
  "Hof": { telefon: "09281 14495-0", email: "Poststelle.RSt_Hof@thw.de" },
  "Homberg": { telefon: "05681 93117-0", email: "Poststelle.RSt_Homberg@thw.de" },
  "Ingolstadt": { telefon: "0228 9945324-0", email: "Poststelle.RSt_Ingolstadt@thw.de" },
  "Karlsruhe": { telefon: "0721 824875-0", email: "Poststelle.RSt_Karlsruhe@thw.de" },
  "Karlstadt": { telefon: "09353 98482-0", email: "Poststelle.RSt_Karlstadt@thw.de" },
  "Kempten": { telefon: "0831 540749-0", email: "Poststelle.RSt_Kempten@thw.de" },
  "Koblenz": { telefon: "0261 889967-0", email: "Poststelle.RSt_Koblenz@thw.de" },
  "Köln": { telefon: "02203 98885-0", email: "Poststelle.RSt_Koeln@thw.de" },
  "Leipzig": { telefon: "0228 9945824 0", email: "Poststelle.RSt_Leipzig@thw.de" },
  "Lingen": { telefon: "0591 800379-0", email: "Poststelle.RSt_Lingen@thw.de" },
  "Lübeck": { telefon: "0451 486697 0", email: "Poststelle.RSt_Luebeck@thw.de" },
  "Magdeburg": { telefon: "0391 611989 0", email: "Poststelle.RSt_Magdeburg@thw.de" },
  "Mannheim": { telefon: "0621 484009-0", email: "Poststelle.RSt_Mannheim@thw.de" },
  "Merzig": { telefon: "06861 91139-0", email: "Poststelle.RSt_Merzig@thw.de" },
  "Mönchengladbach": { telefon: "02161 47764-0", email: "Poststelle.RSt_Moenchengladbach@thw.de" },
  "Mühldorf": { telefon: "08631 18620-0", email: "Poststelle.RSt_Muehldorf@thw.de" },
  "München": { telefon: "089 630216-0", email: "Poststelle.RSt_Muenchen@thw.de" },
  "Münster": { telefon: "0228 9945530-0", email: "Poststelle.Rst_Muenster@thw.de" },
  "Neumünster": { telefon: "04321 85134 0", email: "Poststelle.RSt_Neumuenster@thw.de" },
  "Neustadt a.d.W.": { telefon: "06321 48411-0", email: "Poststelle.RSt_Neustadt_w@thw.de" },
  "Nürnberg": { telefon: "0911 965334-0", email: "Poststelle.RSt_Nuernberg@thw.de" },
  "Oldenburg": { telefon: "0441 212141-0", email: "Poststelle.RSt_Oldenburg@thw.de" },
  "Olpe": { telefon: "0228 9945531-0", email: "Poststelle.RSt_Olpe@thw.de" },
  "Potsdam": { telefon: "03329 69607-0", email: "Poststelle.RSt_Potsdam@thw.de" },
  "Saarbrücken": { telefon: "0681 50082-0", email: "Poststelle.RSt_Saarbruecken@thw.de" },
  "Schleswig": { telefon: "04621 30500-0", email: "Poststelle.RSt_Schleswig@thw.de" },
  "Schwandorf": { telefon: "09431 38596-0", email: "Poststelle.RSt_Schwandorf@thw.de" },
  "Schwerin": { telefon: "0385 305196-0", email: "Poststelle.RSt_Schwerin@thw.de" },
  "Stralsund": { telefon: "03831 28211-0", email: "Poststelle.RSt_Stralsund@thw.de" },
  "Straubing": { telefon: "09421 96341-0", email: "Poststelle.RSt_Straubing@thw.de" },
  "Stuttgart": { telefon: "0711 849608-0", email: "Poststelle.RSt_Stuttgart@thw.de" },
  "Trier": { telefon: "0651 824980-0", email: "Poststelle.RSt_Trier@thw.de" },
  "Tübingen": { telefon: "07071 9135-0", email: "Poststelle.RSt_Tuebingen@thw.de" },
  "Verden": { telefon: "04231 93763-0", email: "Poststelle.RSt_Verden@thw.de" },
  "Villingen-Schwenningen": { telefon: "07721 20289-0", email: "Poststelle.RSt_Vschwenningen@thw.de" },
  "Wesel": { telefon: "0281 319284-0", email: "Poststelle.RSt_Wesel@thw.de" },
};

/** Landesverbandsname → Kontaktdaten. */
export const THW_LANDESVERBAENDE_KONTAKT: Record<string, StelleKontakt> = {
  "Baden-Württemberg": { telefon: "0711 95555-0", email: "Poststelle.LVBW@thw.de" },
  "Bayern": { telefon: "0228 994531-0", email: "Poststelle.LVBY@thw.de" },
  "Berlin, Brandenburg, Sachsen-Anhalt": { telefon: "030 30682 0", email: "Poststelle.LVBEBBST@thw.de" },
  "Bremen, Niedersachsen": { telefon: "0511 33690-0", email: "Poststelle.LVHBNI@thw.de" },
  "Hamburg, Mecklenburg-Vorpommern, Schleswig-Holstein": { telefon: "0431 57933-0", email: "Poststelle.LVHHMVSH@thw.de" },
  "Hessen, Rheinland-Pfalz, Saarland": { telefon: "06131 9297 0", email: "Poststelle.LVHERPSL@thw.de" },
  "Nordrhein-Westfalen": { telefon: "02103 7910-0", email: "Poststelle.LVNW@thw.de" },
  "Sachsen, Thüringen": { telefon: "03447 5684-0", email: "Poststelle.LVSNTH@thw.de" },
};
