/**
 * THW-Funktionen aus der Funktionsliste des THW, Inlandsbereiche
 * (85 STAN-Positionen als Grundfunktion, 60 Zusatz-/sonstige Funktionen).
 *
 * GENERIERT — nicht von Hand bearbeiten.
 * Quelle: scripts/quellen/thw-funktionen.csv (vom Nutzer bereitgestellt).
 * Neu erzeugen mit:  npx tsx scripts/thw-funktionen-vokabular.mts
 *
 * Ergänzt die Handredaktion in thw.ts, die die geläufigen Funktionen mit
 * eigenen Kurzformen und den Codes 1–102 abdeckt. Codes ab 200 sind
 * append-only: Der Generator übernimmt vorhandene Zuordnungen unverändert,
 * damit gespeicherte Bögen und alte QR-Codes weiter auflösen.
 * "kurz" ist hier die amtliche Kurzbezeichnung der Quelle.
 */

import type { FunktionsEintrag } from "./thw";

export const THW_FUNKTIONEN_ERGAENZUNG: FunktionsEintrag[] = [
  { code: 200, kurz: "AE-He", name: "Alters- und Ehrenhelfer/in", art: "funktion" },
  { code: 201, kurz: "AB", name: "Ausbildungsbeauftragte/r", art: "funktion" },
  { code: 202, kurz: "BÖ", name: "Beauftragte/r für Öffentlichkeitsarbeit", art: "funktion" },
  { code: 203, kurz: "Fü ÖGA", name: "Einheitsführer/in ÖGA", art: "funktion" },
  { code: 204, kurz: "FaBe 1/2", name: "Fachberater/in Stufe 1 und 2", art: "funktion" },
  { code: 205, kurz: "FaBe1/2R", name: "Fachberater/in Stufe 1 und 2 (Reserve)", art: "funktion" },
  { code: 206, kurz: "FaHe ESS", name: "Fachhelfer/in ESS", art: "funktion" },
  { code: 207, kurz: "FaHe MHP", name: "Fachhelfer/in Mobiler-Hochwasser-Pegel", art: "funktion" },
  { code: 208, kurz: "FernMel", name: "Fernmelder/in", art: "funktion" },
  { code: 209, kurz: "GrFü Bel", name: "Gruppenführer/in Beleuchtung", art: "funktion" },
  { code: 210, kurz: "GrFü B", name: "Gruppenführer/in Bergung", art: "funktion" },
  { code: 211, kurz: "GrFü B 2", name: "Gruppenführer/in Bergung 2", art: "funktion" },
  { code: 212, kurz: "GrFü BT", name: "Gruppenführer/in Bergungstauchen", art: "funktion" },
  { code: 213, kurz: "GrFü BrB", name: "Gruppenführer/in Brückenbau", art: "funktion" },
  { code: 214, kurz: "GrFü E", name: "Gruppenführer/in Elektroversorgung", art: "funktion" },
  { code: 215, kurz: "GrFü SEE", name: "Gruppenführer/in Fachgruppe SEEBA", art: "funktion" },
  { code: 216, kurz: "GrFü F", name: "Gruppenführer/in Führungsunterstützung", art: "funktion" },
  { code: 217, kurz: "GrFü I", name: "Gruppenführer/in Infrastruktur", art: "funktion" },
  { code: 218, kurz: "GrFü K", name: "Gruppenführer/in Kommunikation", art: "funktion" },
  { code: 219, kurz: "GrFüLogMW", name: "Gruppenführer/in Logistik-Materialwirtschaft", art: "funktion" },
  { code: 220, kurz: "GrFüLogV", name: "Gruppenführer/in Logistik-Verpflegung", art: "funktion" },
  { code: 221, kurz: "GrFü MT", name: "Gruppenführer/in Media Team", art: "funktion" },
  { code: 222, kurz: "GrFü N", name: "Gruppenführer/in Notversorgung und Notinstandsetzung", art: "funktion" },
  { code: 223, kurz: "GrFü ÖGA", name: "Gruppenführer/in ÖGA", art: "funktion" },
  { code: 224, kurz: "GrFü Öl", name: "Gruppenführer/in Ölschaden", art: "funktion" },
  { code: 225, kurz: "GrFü O", name: "Gruppenführer/in Ortung", art: "funktion" },
  { code: 226, kurz: "GrFü R", name: "Gruppenführer/in Räumen", art: "funktion" },
  { code: 227, kurz: "GrFü SB", name: "Gruppenführer/in Schwere Bergung", art: "funktion" },
  { code: 228, kurz: "GrFü Sp", name: "Gruppenführer/in Sprengen", art: "funktion" },
  { code: 229, kurz: "GrFü TW", name: "Gruppenführer/in Trinkwasserversorgung", art: "funktion" },
  { code: 230, kurz: "GrFü W", name: "Gruppenführer/in Wassergefahren", art: "funktion" },
  { code: 231, kurz: "GrFü WP", name: "Gruppenführer/in Wasserschaden/Pumpen", art: "funktion" },
  { code: 232, kurz: "HeAw", name: "Helferanwärter/in", art: "funktion" },
  { code: 233, kurz: "JuHe", name: "Junghelfer/in", art: "funktion" },
  { code: 234, kurz: "Ltr FK", name: "Leiter/in Fachgruppe FK", art: "funktion" },
  { code: 235, kurz: "Ltr Log", name: "Leiter/in Fachgruppe Logistik", art: "funktion" },
  { code: 236, kurz: "LdF ÖGA", name: "Leiter/in Fm-Betrieb ÖGA", art: "funktion" },
  { code: 237, kurz: "Koch", name: "OV-Koch/Köchin", art: "funktion" },
  { code: 238, kurz: "OB", name: "Ortsbeauftragte/r", art: "funktion" },
  { code: 239, kurz: "OJB", name: "Ortsjugendbeauftragte/r", art: "funktion" },
  { code: 240, kurz: "PsFk (R)", name: "Psychosoziale Fachkraft (Reserve)", art: "funktion" },
  { code: 241, kurz: "S 6/FeFü", name: "Sachgebietsleiter/in 6 / Fernmeldeführer/in", art: "funktion" },
  { code: 242, kurz: "SM", name: "Schirrmeister/in", art: "funktion" },
  { code: 243, kurz: "SPLtr", name: "Stützpunktleiter/in", art: "funktion" },
  { code: 244, kurz: "Peer (R)", name: "THW-Peer (Reserve)", art: "funktion" },
  { code: 245, kurz: "TrFü Bel", name: "Truppführer/in Beleuchtung", art: "funktion" },
  { code: 246, kurz: "TrFü B", name: "Truppführer/in Bergung", art: "funktion" },
  { code: 247, kurz: "TrFü B S", name: "Truppführer/in Bergung der Fachgruppe SEEBA", art: "funktion" },
  { code: 248, kurz: "TrFü BT", name: "Truppführer/in Bergungstauchen", art: "funktion" },
  { code: 249, kurz: "TrFü BrB", name: "Truppführer/in Brückenbau", art: "funktion" },
  { code: 250, kurz: "TrFü ESS", name: "Truppführer/in Einsatzstellensicherung", art: "funktion" },
  { code: 251, kurz: "TrFü E", name: "Truppführer/in Elektroversorgung", art: "funktion" },
  { code: 252, kurz: "TrFü FmT", name: "Truppführer/in Fernmeldetrupp", art: "funktion" },
  { code: 253, kurz: "TrFü FuK", name: "Truppführer/in Führungs-/Kommunikationstrupp", art: "funktion" },
  { code: 254, kurz: "TrFü Fü", name: "Truppführer/in Führungstrupp", art: "funktion" },
  { code: 255, kurz: "TrFü F", name: "Truppführer/in Führungsunterstützung", art: "funktion" },
  { code: 256, kurz: "TrFü I", name: "Truppführer/in Infrastruktur", art: "funktion" },
  { code: 257, kurz: "TrFü K", name: "Truppführer/in Kommunikation", art: "funktion" },
  { code: 258, kurz: "TrFü Log", name: "Truppführer/in Logistik", art: "funktion" },
  { code: 259, kurz: "TrFüLogMW", name: "Truppführer/in Logistik-Materialwirtschaft", art: "funktion" },
  { code: 260, kurz: "TrFüLogV", name: "Truppführer/in Logistik-Verpflegung", art: "funktion" },
  { code: 261, kurz: "TrFü MT", name: "Truppführer/in Media Team", art: "funktion" },
  { code: 262, kurz: "TrFü MHP", name: "Truppführer/in Mobiler Hochwasserpegel", art: "funktion" },
  { code: 263, kurz: "TrFü N", name: "Truppführer/in Notversorgung und Notinstandsetzung", art: "funktion" },
  { code: 264, kurz: "TrFü ÖGA", name: "Truppführer/in ÖGA", art: "funktion" },
  { code: 265, kurz: "TrFü Öl", name: "Truppführer/in Ölschaden", art: "funktion" },
  { code: 266, kurz: "TrFü O", name: "Truppführer/in Ortung", art: "funktion" },
  { code: 267, kurz: "TrFü O S", name: "Truppführer/in Ortung der Fachgruppe SEEBA", art: "funktion" },
  { code: 268, kurz: "TrFü R", name: "Truppführer/in Räumen", art: "funktion" },
  { code: 269, kurz: "TrFü SB", name: "Truppführer/in Schwere Bergung", art: "funktion" },
  { code: 270, kurz: "TrFü TS", name: "Truppführer/in Schwerer Transport", art: "funktion" },
  { code: 271, kurz: "TrFü Sp", name: "Truppführer/in Sprengen", art: "funktion" },
  { code: 272, kurz: "TrFü TW", name: "Truppführer/in Trinkwasserversorgung", art: "funktion" },
  { code: 273, kurz: "TrFü UL", name: "Truppführer/in Unbemannte Luftfahrtsysteme", art: "funktion" },
  { code: 274, kurz: "TrFü W", name: "Truppführer/in Wassergefahren", art: "funktion" },
  { code: 275, kurz: "TrFü WP", name: "Truppführer/in Wasserschaden/Pumpen", art: "funktion" },
  { code: 276, kurz: "TrFü WV", name: "Truppführer/in Weitverkehrstrupp", art: "funktion" },
  { code: 277, kurz: "TrFü FGe", name: "Truppführer/in-Führungsgehilfe", art: "funktion" },
  { code: 278, kurz: "VwB", name: "Verwaltungsbeauftragte/r", art: "funktion" },
  { code: 279, kurz: "ZFü FZ FK", name: "Zugführer/in Fachzug Führung/Kommunikation", art: "funktion" },
  { code: 280, kurz: "ZFüFZLog", name: "Zugführer/in Fachzug Logistik", art: "funktion" },
  { code: 281, kurz: "ZTrFü FK", name: "Zugtruppführer/in Fachzug Führung/Kommunikation", art: "funktion" },
  { code: 282, kurz: "ZTrFüLog", name: "Zugtruppführer/in Fachzug Logistik", art: "funktion" },
  { code: 283, kurz: "stv. OB", name: "stv. Ortsbeauftragte/r", art: "funktion" },
  { code: 284, kurz: "stv. OJB", name: "stv. Ortsjugendbeauftragte/r", art: "funktion" },
  { code: 285, kurz: "AS GerW", name: "Atemschutz-Gerätewart/in", art: "zusatz" },
  { code: 286, kurz: "AusMotSä", name: "Ausbilder/in Bediener/in Motorsäge", art: "zusatz" },
  { code: 287, kurz: "ABO", name: "Ausbilder/in Biologische Ortung", art: "zusatz" },
  { code: 288, kurz: "AusbGA", name: "Ausbilder/in Grundausbildung", art: "zusatz" },
  { code: 289, kurz: "BPLogBGR", name: "Befähigte Person - BGR 500 (FGr Log)", art: "zusatz" },
  { code: 290, kurz: "BA AS", name: "Bereichsausbilder/in Atemschutz", art: "zusatz" },
  { code: 291, kurz: "BA IT", name: "Bereichsausbilder/in IT", art: "zusatz" },
  { code: 292, kurz: "BA Koch", name: "Bereichsausbilder/in Koch", art: "zusatz" },
  { code: 293, kurz: "BA Kf", name: "Bereichsausbilder/in Kraftfahrwesen", art: "zusatz" },
  { code: 294, kurz: "BA SprFu", name: "Bereichsausbilder/in Sprechfunk", art: "zusatz" },
  { code: 295, kurz: "BezJB", name: "Bezirksjugendbeauftragte/r", art: "zusatz" },
  { code: 296, kurz: "BJB", name: "Bundesjugendbeauftragte/r", art: "zusatz" },
  { code: 297, kurz: "BuJL", name: "Bundesjugendleiter/in", art: "zusatz" },
  { code: 298, kurz: "BJSp", name: "Bundesjugendsprecher/in", art: "zusatz" },
  { code: 299, kurz: "BS", name: "Bundessprecher/in", art: "zusatz" },
  { code: 300, kurz: "ELA", name: "Einsatzleiter/in Ausland", art: "zusatz" },
  { code: 301, kurz: "GerW", name: "Gerätewart/in", art: "zusatz" },
  { code: 302, kurz: "HeSpr", name: "Helfersprecher/in", art: "zusatz" },
  { code: 303, kurz: "ITB", name: "IT-Betreuer/in", art: "zusatz" },
  { code: 304, kurz: "Koch Ausl", name: "Koch/Köchin Ausland", art: "zusatz" },
  { code: 305, kurz: "KB", name: "Kreisbeauftragte/r", art: "zusatz" },
  { code: 306, kurz: "LJB", name: "Landesjugendbeauftragte/r", art: "zusatz" },
  { code: 307, kurz: "LS", name: "Landessprecher/in", art: "zusatz" },
  { code: 308, kurz: "PGA", name: "Prüfer/in Grundausbildung", art: "zusatz" },
  { code: 309, kurz: "PRH", name: "Prüfer/in Rettungshunde", art: "zusatz" },
  { code: 310, kurz: "PLGA", name: "Prüfungsleiter/in Grundausbildung", art: "zusatz" },
  { code: 311, kurz: "SiBe", name: "Sicherheitsbeauftragte/r", art: "zusatz" },
  { code: 312, kurz: "SiFa", name: "Sicherheitsfachkraft", art: "zusatz" },
  { code: 313, kurz: "SvP-OV", name: "Sonstige verantwortliche Person Gefahrgut", art: "zusatz" },
  { code: 314, kurz: "UmwAud", name: "Umweltauditor/in", art: "zusatz" },
  { code: 315, kurz: "Ver DS", name: "Verantwortliche/r für den Dienstsport", art: "zusatz" },
  { code: 316, kurz: "stvBezJB", name: "stv. Bezirksjugendbeauftragte/r", art: "zusatz" },
  { code: 317, kurz: "stv. BJB", name: "stv. Bundesjugendbeauftragte/r", art: "zusatz" },
  { code: 318, kurz: "stv BuJL", name: "stv. Bundesjugendleiter/in", art: "zusatz" },
  { code: 319, kurz: "stv BJSp", name: "stv. Bundesjugendsprecher/in", art: "zusatz" },
  { code: 320, kurz: "stv BS", name: "stv. Bundessprecher/in", art: "zusatz" },
  { code: 321, kurz: "stvHeSpr", name: "stv. Helfersprecher/in", art: "zusatz" },
  { code: 322, kurz: "stv. LJB", name: "stv. Landesjugendbeauftragte/r", art: "zusatz" },
  { code: 323, kurz: "stv LS", name: "stv. Landessprecher/in", art: "zusatz" },
  { code: 324, kurz: "ABC-FaHe", name: "ABC-Fachhelfer/in", art: "zusatz" },
  { code: 325, kurz: "Bau ESS", name: "Baufachberater/in ESS", art: "zusatz" },
  { code: 326, kurz: "BoFüSee", name: "Bootsführer/in THW See", art: "zusatz" },
  { code: 327, kurz: "E-Schw.", name: "Elektro-Schweißer/in", art: "zusatz" },
  { code: 328, kurz: "FaBe 3/4", name: "Fachberater/in Stufe 3 und 4", art: "zusatz" },
  { code: 329, kurz: "G-Schw.", name: "Gas-Schweißer/in", art: "zusatz" },
  { code: 330, kurz: "G-S. 1BG", name: "Gas-Schweißer/in 1. Bergungsgruppe", art: "zusatz" },
  { code: 331, kurz: "GerWLogV", name: "Gerätewart/in Logistikstelle Verpflegung", art: "zusatz" },
  { code: 332, kurz: "HygFa", name: "Hygiene-Fachkraft", art: "zusatz" },
  { code: 333, kurz: "Kf Häg", name: "Kraftfahrer/in Hägglunds", art: "zusatz" },
  { code: 334, kurz: "KüHe", name: "Küchenhelfer/in", art: "zusatz" },
  { code: 335, kurz: "LehrTau", name: "Lehrtaucher/in", art: "zusatz" },
  { code: 336, kurz: "LtrStabE", name: "Leiter/in Stab THW Führungsstelle (Einsatz)", art: "zusatz" },
  { code: 337, kurz: "LtrFüStE", name: "Leiter/in einer THW-Führungsstelle (Einsatz)", art: "zusatz" },
  { code: 338, kurz: "Masch DL", name: "Maschinist/in Drucklufterzeuger", art: "zusatz" },
  { code: 339, kurz: "OrtHe", name: "Ortungshelfer/in", art: "zusatz" },
  { code: 340, kurz: "RechFü", name: "Rechnungsführer/in", art: "zusatz" },
  { code: 341, kurz: "S1-4", name: "Sachgebietsleiter/in 1-4", art: "zusatz" },
  { code: 342, kurz: "SM(SBA)", name: "Schirrmeister/in (SEEBA)", art: "zusatz" },
  { code: 343, kurz: "TeBe ABC", name: "Technische/r Berater/in Bergung ABC", art: "zusatz" },
  { code: 344, kurz: "TeBeDe", name: "Technische/r Berater/in Deichverteidigung", art: "zusatz" },
];
